### ISSUE TITLE
Working files on main branch shouldn't be zipped

### ISSUE THREAD

**Issue by notoriousjere** [MaxLastBreath/TOTK-mods#1]
Hey, now that this is on github, is there any reason to keep the mod folder zipped up within the source code files? You could zip it for the releases, but keep the individual files in the mod folder as they are so the diff can be tracked more easily, and the files can be browsed on github. We'd also be able to just run `git pull`  in our terminal to get the latest version for those who don't want to have to keep downloading zip files.

Thanks!

**Comment by MaxLastBreath** [comment]
I'll work on it, just been a bit busy lately :)

**Comment by MaxLastBreath** [comment]
Done
