### ISSUE TITLE
[Feature request] Custom resolution option

### ISSUE THREAD

**Issue by InterClaw** [MaxLastBreath/TOTK-mods#100]
Any plans on adding the possibility of adding a custom resolution in TOTK Optimizer? I'm interested in running 3840x1600.

**Comment by MaxLastBreath** [comment]
You can do that by using the aspect ratios combined with the preset resolution i guess? Or could just change it manually in the config file of the mod itself, hence it does support custom resolution, it would just be a clutter in the UI

**Comment by MaxLastBreath** [comment]
There's a new addition for more aspect ratios, this should hopefully give enough options for the moment
