### ISSUE TITLE
Screenshot resolution in yuzu is limited to 1080p.

### ISSUE THREAD

**Issue by rarikuma** [MaxLastBreath/TOTK-mods#103]
Even if I set the resolution to 4K with TOTK Optimizer 2.0.4, the resolution of the screenshot image taken with yuzu is 1080p.

In TOTK Optimizer 1.5.5, yuzu was able to take screenshots at 4K resolution and this problem did not exist.

I know there is an alternative of using other screenshot taking software, but I don't want to do so if possible, as I think using the built-in screenshot function of the emulator would be the best in terms of image quality.

I hope that the TOTK Optimizer will be fixed so that I can take screenshots in 4K resolution with yuzu again.

**Comment by MaxLastBreath** [comment]
The game is rendering at native 4k resolution, that's an emulator issue and not related to the optimizer, if you have an Nvidia gpu and their newest Nvidia app or Geforce experience just use alt+f1

**Comment by rarikuma** [comment]
Understood.

Until yuzu's successor software resolves this issue, I will use other screenshot taking software.

By the way, TOTK Optimizer 1.5.5 (UPSCALING VERSION: UltraCam) was able to take 4K resolution screenshots with yuzu, does this mean that the rendered 4K resolution in this version was not native 4K resolution?

**Comment by MaxLastBreath** [comment]
> Understood.
> 
> Until yuzu's successor software resolves this issue, I will use other screenshot taking software.
> 
> By the way, TOTK Optimizer 1.5.5 (UPSCALING VERSION: UltraCam) was able to take 4K resolution screenshots with yuzu, does this mean that the rendered 4K resolution in this version was not native 4K resolution?

Yup 1.5.5 was using the emulator's upscaler and then fixing up some stuff in game, now the game is actually running at 4K and then yuzu is a translational layer for that resolution, therefore yuzu doesn't think it's actually running at 4k right now, despite the window and the viewports being at 4K. This should be fixable on Yuzu's end but it'll require some code being written for it... Unfortunately we lost that amazing team that worked on Yuzu
