### ISSUE TITLE
Invisible Link

### ISSUE THREAD

**Issue by techsoulhack** [MaxLastBreath/TOTK-mods#107]
After applying recommended optimizations for my hardware and loading into my existing save file, Link is only viewable from random angles, otherwise he goes invisible and only his shadow remains.

**Comment by MaxLastBreath** [comment]
That sounds like a bug with either game rom or emulator, thousands of people using the mod and I've never heard/seen this issue

**Comment by giptorres** [comment]
I'm using sudachi and also have this problem when applying the mod using the .exe

**Comment by MaxLastBreath** [comment]
> I'm using sudachi and also have this problem when applying the mod using the .exe, might be a sudachi only issue?

Very possible.
