### ISSUE TITLE
[Bug]: Game World Not Loading

### ISSUE THREAD

**Issue by Plexxl** [MaxLastBreath/TOTK-mods#109]
### Describe the bug

```bash
1. The game world does not load after loading a save/creating a new save
...
```

### Reproduction steps

```bash
1. Use TotK Optimizer
2. Select default options in TotK Optimizer
...
```

### Additional context

```bash
1. The game is running (you are still able to see Link's location arrow on the loading screen pulse)
2. I am using Nvidia GPU
...
```

### What's your operating system?

Windows 11

**Comment by MaxLastBreath** [comment]
Hello, please remove your game file and reinstall it, this is a problem with the Yuzu emulator and it's forks... All of them have this problem, alternative try tweaking the resolution or try with the default settings

**Comment by Plexxl** [comment]
What do you mean by removing the game file?

**Comment by MaxLastBreath** [comment]
Update file*

**Comment by Plexxl** [comment]
Ah

**Comment by Plexxl** [comment]
Okay, so I was able to load the game world without Update 1.2.1, but when I reenabled it, the game still froze

**Comment by Plexxl** [comment]
I am using the EmuDeck installation of Yuzu.

**Comment by Plexxl** [comment]
Update: Still doesn't work with Suyu

**Comment by MaxLastBreath** [comment]
Have you tried deleting the file and then reinstalling it? Not just enable/disable, delete it entirely. Its a confirmed bug in Suyu the developers said so yesterday.

**Comment by Plexxl** [comment]
I removed all update files and did a clean install of the mods. Loads with version 1.0.0 but no FoV or blackscreen fix

**Comment by MaxLastBreath** [comment]
1.0.0 isn't supported.
