### ISSUE TITLE
[Bug]: Optimizer fps going rogue and crashing with suyu emulator

### ISSUE THREAD

**Issue by BigFlashBangy48** [MaxLastBreath/TOTK-mods#111]
### Describe the bug

```bash
The optimizer doesn't lock fps and the game is triple speed at 200 fps on suyu emulator
```

### Reproduction steps

```bash
apply fps mod to suyu emulator
```

### What's your operating system?

Windows 11

**Comment by MaxLastBreath** [comment]
Shouldn't this issue be going to the Yuzu dev team and not here? Yuzu is a fork of Yuzu and Yuzu runs perfectly fine with ultracam and the optimizer, therefore I don't see how this my problem.

**Comment by BigFlashBangy48** [comment]
Yeah it worked fine on Yuzu Im talking about Suyu compatibility

**Comment by MaxLastBreath** [comment]
If the mod works fine on Yuzu,, Ryujinx and even on the switch, where would the problem be?

**Comment by BigFlashBangy48** [comment]
On Suyu
