### ISSUE TITLE
add the ability to set resolution to 360p/540p

### ISSUE THREAD

**Issue by CheeseisYummy1234** [MaxLastBreath/TOTK-mods#113]
I have very low specs(i7 3610qm, gt 630m)
not being able to set the resolution in the optimizer to 540p/360p is frustrating because I get worse performance, please add the feature to set resolution to 360p/540p

**Comment by MaxLastBreath** [comment]
you could manually change the setting in !!!TOTKOptimizer folder

**Comment by CheeseisYummy1234** [comment]
How would I manually change the setting?
when I opened the config for the optimizer mod it says resolution 1, when i try put it at 0.5 it doesn't do anything. Is there another file I need to edit to change the res to 360p?

**Comment by MaxLastBreath** [comment]
> How would I manually change the setting? when I opened the config for the optimizer mod it says resolution 1, when i try put it at 0.5 it doesn't do anything. Is there another file I need to edit to change the res to 360p?

Yes inside of the mod itself in your emulator's folder not in the Optimizer

**Comment by CheeseisYummy1234** [comment]
I found it, ty
