### ISSUE TITLE
Compatibility for suzu!?

### ISSUE THREAD

**Issue by PickMeNow** [MaxLastBreath/TOTK-mods#114]
**Is your feature request related to a problem? - Yes
 - I tried to load the same Mods from yuzu to suzu but I noticed it hangs while loading the game, this doesn't not happen in yuzu, wanted to make sure totk-optimizer is compatible with suzu. Without mods the game loaded correctly.

**Describe the solution you'd like**
Wanted the TOTK-Optimizer to have full compatibility with suzu and future versions, since I believe it will be the future replacement for yuzu.

**Describe alternatives you've considered**
I also considered ryujinx, as an viable alternative but the more alternatives the better right?? *Wink* *Wink*

**Additional context**
Would be great if TOTK-Optimizer could apply settings as it did with yuzu, just by settings the options and clicking apply.

**Comment by MaxLastBreath** [comment]
Yes it is compatible, the Emulator itself has an issue. Remove the tears of the kingdom update file, by completely deleting it not just disabling it and then reinstall it.

**Comment by MaxLastBreath** [comment]
Also the optimizer does infact already apply the mandatory settings to ryujinx, but ryujinx barely has settings to change, so it doesn't justify presets for Ryujinx.

**Comment by PickMeNow** [comment]
I tried what you suggested, removed installed update and also dlc, installed the update 1.2.1, went to yuzu load folder to copy the mods applied by TOTKOptimizer but still hangs...  

I am using suzu.AppImage and TOTKOptimizer.AppImage not sure if this helps

**Comment by MaxLastBreath** [comment]
Not much else i can do it's an issue on the emulator side unfortunately.

**Comment by thejaykid7** [comment]
just wanted to chime in and mention that your suggestion about wiping the updates addon seems to work

**Comment by ArsenicBismuth** [comment]
Tested this on my side, got an issue where it hangs on loading screen. Fixed by removing my update (Right Click TotK > Remove > Update) and reapplying it again.
