### ISSUE TITLE
[Bug]: Playstation UI mod in Optimizer causes signs to have missing arrows in suyu

### ISSUE THREAD

**Issue by dxgldotorg** [MaxLastBreath/TOTK-mods#119]
### Describe the bug

```bash
When adding the Playstation UI Mod in TOTK Optimizer 2.0.5 the arrows on signs get replaced with question marks.
```

### Reproduction steps

```bash
Run TOTK Optimizer with the following settings:
Legacy mode, FPS 60, Menu FPS 60, FOV 50, Resolution 4k, Shadow Resolution 2048x, Aspect ratio 16x9, Render Distance DEFAULT, UI Playstation UI, checked Quality Improvements and Disable Fxaa

Running suyu Git build.

Disabling the Playstation UI component in suyu fixes the problem; TOTK Optimizer mod directory works fine.  Problem also exists if only the Playstation UI mod is enabled.
```

### What's your operating system?

Windows 11

**Comment by dxgldotorg** [comment]
Screenshot:
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/7480507/814dbfb5-d2a3-4da2-85d7-1632d2c4cb44)

**Comment by MaxLastBreath** [comment]
does it happen with different aspect ratios too?

**Comment by dxgldotorg** [comment]
I haven't tried different aspect ratios; does that affect the Playstation UI mod folder?

Also, it does appear that the mod used in your emulator was taken down by its author.  Game version is 1.2.1 which appears to not be listed in the config.yaml of the Playstation UI mod.

**Comment by MaxLastBreath** [comment]
> I haven't tried different aspect ratios; does that affect the Playstation UI mod folder?
> 
> Also, it does appear that the mod used in your emulator was taken down by its author. Game version is 1.2.1 which appears to not be listed in the config.yaml of the Playstation UI mod.

yes the author has completely disappeared, nothing we can do about that. Regardless, if u can try a different aspect ratio since they use different mods altogether, would be appreciated!

**Comment by brentward** [comment]
I'm having the same issue so I tested multiple aspect ratios and they all exhibited the issue. I tested 4x3, 16x10, 19.5x9, 21x9, and 21.5x9. I took screenshots with all of them, but they all look exactly the same as the one already posted in this bug report.

Let me know if the screenshots are useful and I'll post them or if there is anything else I can do to help.

**Comment by dxgldotorg** [comment]
> I'm having the same issue so I tested multiple aspect ratios and they all exhibited the issue. I tested 4x3, 16x10, 19.5x9, 21x9, and 21.5x9. I took screenshots with all of them, but they all look exactly the same as the one already posted in this bug report.
> 
> Let me know if the screenshots are useful and I'll post them or if there is anything else I can do to help.

It appears this because the DualSense UI mod replaces a few font files, but some changes were made in 1.2.1 breaking the arrow characters.  Perhaps someone could apply the changes against the latest font files?

**Comment by MaxLastBreath** [comment]
> > I'm having the same issue so I tested multiple aspect ratios and they all exhibited the issue. I tested 4x3, 16x10, 19.5x9, 21x9, and 21.5x9. I took screenshots with all of them, but they all look exactly the same as the one already posted in this bug report.
> > Let me know if the screenshots are useful and I'll post them or if there is anything else I can do to help.
> 
> It appears this because the DualSense UI mod replaces a few font files, but some changes were made in 1.2.1 breaking the arrow characters. Perhaps someone could apply the changes against the latest font files?

Yeah that makes sense

**Comment by brentward** [comment]
Just for reference I am using 1.2.0 of the game, not 1.2.1. Does anyone know what version the breaking change occurred in?

**Comment by brentward** [comment]
I tried all of the older patches, i.e. 1.1.0, 1.1.1, 1.1.2, and 1.2.0, and arrows glyphs are missing from the signs in all of them so the hypothesis of breaking changes doesn't seem accurate.
