### ISSUE TITLE
error in running TOTK optimizer 1.3.0

### ISSUE THREAD

**Issue by choron2** [MaxLastBreath/TOTK-mods#13]
i have downloaded the optimizer and tried running it. it opens up cmd but closes in 1 second. 
i have attached the error for your reference
<img width="566" alt="Screenshot 2023-09-01 192106" src="https://github.com/MaxLastBreath/TOTK-mods/assets/143804542/bec8ec6c-5030-4dee-ad5e-500680349776">

**Comment by Davo-cado** [comment]
Experiencing the same issue

**Comment by MaxLastBreath** [comment]
Looking into it, gonna release a fix soon.

**Comment by MaxLastBreath** [comment]
[Should be Fixed](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.3.1)

**Comment by choron2** [comment]
thank you for your help and hard work!

**Comment by MaxLastBreath** [comment]
> thank you for your help and hard work!

Thank you as well for reporting the issues! Having these issues reported, makes it easier to fix them :)
