### ISSUE TITLE
[Bug]: High Preset Randomly Crashing on Ryujinx due to `System.AccessViolationException`

### ISSUE THREAD

**Issue by jasondyoungberg** [MaxLastBreath/TOTK-mods#130]
### Describe the bug

My game will randomly crash after playing for around 1 hour.

```
cmd : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an 
indication that other memory is corrupt.
```

### Reproduction steps

1. Choose the high preset
2. Play the game for ~1 hour
3. The game freezes then closes

### Additional context

I'm using Ryujinx 1.1.1298 and Optimizer 2.0.5

[stderr.log](https://github.com/MaxLastBreath/TOTK-mods/files/15265031/stderr.log)
[stdout.log](https://github.com/MaxLastBreath/TOTK-mods/files/15265032/stdout.log)
[maxlastbreath.ini](https://github.com/MaxLastBreath/TOTK-mods/files/15265035/maxlastbreath.ini.txt)

### What's your operating system?

Windows 11

**Comment by MaxLastBreath** [comment]
May want to report this to ryujinx, they have an issue with texture cache being too small at times

**Comment by jasondyoungberg** [comment]
I got a temporary fix that seems to be working. I changed [this constant](https://github.com/Ryujinx/Ryujinx/blob/a23d8cb92f3f1bb8dc144f4d9fb3fddee749feae/src/Ryujinx.Graphics.Gpu/Image/AutoDeleteCache.cs#L49) to `1536 * 1024 * 1024`

**Comment by MaxLastBreath** [comment]
Yee remember I told you on discord, it is the texture cache haha, hopefully one of the devs will bring a more permanent fix in the future tho

**Comment by jasondyoungberg** [comment]
Yeah, I created a feature request on ryujinx. https://github.com/Ryujinx/Ryujinx/issues/6798

**Comment by Westronin** [comment]
Hi, I'm having this exact same issue on TOTK with Ryujinx.

Did you ever find a fix? I tried to check the link for the line that you changed to 1536 * 1024 * 1024 but the link is dead.

If you could help that would be very much appreciated ! Thank you !
