### ISSUE TITLE
[Bug]: Stuck on launching screen isssue

### ISSUE THREAD

**Issue by Gasterboi** [MaxLastBreath/TOTK-mods#132]
### Describe the bug

```bash
1.whenever i install this mod, my game runs but stays at the launching screen, so all i see is the switch logo
2.
3.
...
```

### Reproduction steps

```bash
1.before i was able to play, but now it wont launch.
2.to be sure it was the mod, i disabled it, and it worked, i dont know what to do
3.
...
```

### Additional context

```bash
1.i use yuzu
2.
3.
...
```

### What's your operating system?

Windows 11

**Comment by MaxLastBreath** [comment]
Uninstall update file and then reinstall the update file, this issue is an emulator issue. Specifically yuzu derived emulators.

**Comment by iamse7en** [comment]
I'm having this issue too with a Windows 10 machine, and reinstalling update does work. But I need to uninstall/reinstall update _every time_ I launch sudachi. Otherwise it is stuck on "launching screen." Very bizarre. I also increased memory to 6GB. Any ideas/suggestions @MaxLastBreath ? Thanks!

**Comment by Xyttra** [comment]
I have the same issue with Sudachi. Playing TotK. Uninstalling the update (1.2.1) works, but the issue returns upon reinstalling the update.
