### ISSUE TITLE
Ultracam 1.0.0 support

### ISSUE THREAD

**Issue by i-can-not-program** [MaxLastBreath/TOTK-mods#133]
**Is your feature request related to a problem? Please describe.**
I like playing on 1.0.0 because of the fun glitches and I don't have legal access to any other versions with the same glitches (1.1.1)

**Describe the solution you'd like**
Support for 1.0.0 in UltraCam, pressing ZL+DOWN does nothing

**Describe alternatives you've considered**
there isn't really an alternative other than pirating 1.1.1 which is illegal, and still there are some 1.0.0 exclusive glitches

**Additional context**

**Comment by MaxLastBreath** [comment]
maybe in the future, gonna leave it open for now. Porting UC to 1.0.0 will take a few days to a week+ of work.
