### ISSUE TITLE
[Bug]: Ryujinx crashes after shaders compilation

### ISSUE THREAD

**Issue by Therises** [MaxLastBreath/TOTK-mods#137]
### Describe the bug

When TOTK Optimizer mod is enabled in Mod Manager, Ryujinx crashes after launching the game and compiling shaders with following error: 
```
00:00:28.170 |E| HLE.GuestThread.46 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
```

My specs:
```
System: Windows 10
GPU: NVIDIA GeForce RTX 4090
RAM: 64 GB
CPU:Ryzen 7 5800X3D
TOTK: 1.2.1
Ryujinx: 1.1.1325
```

**Comment by MaxLastBreath** [comment]
This indicates something somewhere is out of bounds, check your settings and ensure to not run anything above the high setting on Ryujinx

**Comment by Therises** [comment]
Yeah, I guess upscaling should be off for this to work 😅

**Comment by MaxLastBreath** [comment]
> Yeah, thanks for the help! I guess upscaling should be off for this to work 😅 Tripple buffer still crashes ryujinx, but after shaders compilation and resolution isn't applied (screenshots (F8) come out at 1080p and there are no visual or performance difference between 1080 / 4k / 8k Oo

8K should just insta crash btw, ryu doesnt have enough memory to push 8k lol, are you using a version over 1.0.0+?

**Comment by Therises** [comment]
> 8K should just insta crash btw, ryu doesnt have enough memory to push 8k lol, are you using a version over 1.0.0+?

TotK Optimizer is v2.0.5 and Ryujinx is 1.1.1330. It looks like it doesn't apply resolution mod(s). Also, there's a download error inside TotK Optimizer console window for `None`. [Here's](https://pastebin.com/hX86Fh0H) my log of it.

**Comment by MaxLastBreath** [comment]
> > 8K should just insta crash btw, ryu doesnt have enough memory to push 8k lol, are you using a version over 1.0.0+?
> 
> TotK Optimizer is v2.0.5 and Ryujinx is 1.1.1330. It looks like it doesn't apply resolution mod(s). Also, there's a download error inside TotK Optimizer console window for `None`. [Here's](https://pastebin.com/hX86Fh0H) my log of it.

Ultracam is downloaded, which is what controls the resolution regardless, the None error is coming from the aspect ratios/UI mods.

Check if !!!TOTKOptimizer mod is applied correctly

**Comment by Therises** [comment]
>Check if !!!TOTKOptimizer mod is applied correctly

FIrst person view can be activated, but I don't see any resolution changes 😅

**Comment by Therises** [comment]
With new version (2.0.7) subjectively the only thing that works is 60fps. Tripple buffer and Remove Depth of Field still crash the Ryujinx. Also, 2.0.5 can't download ULTRACAM Beyond, so even first person view is now unavailable for me.

Won't bugger you anymore, will just use standard Ryujinx upscaler and your 60FPS option

**Comment by MaxLastBreath** [comment]
> With new version (2.0.7) subjectively the only thing that works is 60fps. Tripple buffer and Remove Depth of Field still crash the Ryujinx. Also, 2.0.5 can't download ULTRACAM Beyond, so even first person view is now unavailable for me.
> 
> Won't bugger you anymore, will just use standard Ryujinx upscaler and your 60FPS option.
> 
> I wonder how do **you** test this? Do you use Ryujinx or the last version of Yuzu? If you're using Ryujinx, can you please share your config? (windows/linux, ryujinx version, etc.)

Ultracam beyond is available, first person was a separate mod that included romfs files. So it has been removed alongside with the other romfs mods, I use ryujinx. Triple buffer essentially does nothing on emulator since Ryujinx and other emulators handle buffers on their own, the entire point of the setting is to be used on Switch. Depth of field crashing is a new one.

**Comment by Therises** [comment]
>Ultracam beyond is available

Either I can't figure out how to turn it on or it's plain doesn't work for me. I've tried to press `U` on keyboard (I've enabled `Direct Keyboard Access` inside input settings) and `ZL + ↓` and `L + ↓` - didn't change a thing.

**Comment by Therises** [comment]
@MaxLastBreath Okay, fk me and fk my life. I'm an idiot. I could've sworn I had 1.2.1 enabled, but I hadn't - hence nothing, except FPS mod, worked. Then it crashed on 4k resolution but after howering over it and **actually reading the fkn tooltip** I enabled `Use alternative memory layout` aka `Extended Memory` and now everything works! Thanks for your patience and time 😅

**Comment by MaxLastBreath** [comment]
haha no worries
