### ISSUE TITLE
AppImage: window size is buggy

### ISSUE THREAD

**Issue by ratijas** [MaxLastBreath/TOTK-mods#14]
Launched the latest version on a Steam Deck.

Window opens unusably small, and not resizable. It is kinda possible to maximize it before it fully loads in, but once unmaximized you can not go back. Also, that "maximize" trick does not work on Settings window.

![Screenshot_20230902_120438](https://github.com/MaxLastBreath/TOTK-mods/assets/6737986/7f324e11-3c37-48e4-bd3b-7a003c3e90e0)

No usable errors or warning in terminal either.

---

And now for something completely different: have you considered Qt/QML for graphical interface?

**Comment by MaxLastBreath** [comment]
Thats rather weird, can you open the Manager_Config.ini and paste

[Settings]
scale = Off

if Off doesnt work try scale = 1.0, if theres a setting section already, paste scale under the setting section.

- on the side note, this is actually a really weird bug, the appimage version is constantly being tested on steamdeck. If the config edit doesnt solve it, can you confirm if it happens on older versions as well?

> And now for something completely different: have you considered Qt/QML for graphical interface?

- Ive already written a framework to work with tk, tk isnt the best, but ive already spent a large amount of time making it work, its simply not worth rewriting it currently, it would take too much time for very little gain.

**Comment by MaxLastBreath** [comment]
Should be fixed with [1.3.3 ](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.3.3)

If the issue persists attempt the above, if it still keeps happening, I can't seem to replicate it neither on my VM or steamdeck and a few other VMs. Regardless of settings.

**Comment by ratijas** [comment]
Sorry for going missing. Dealing with mods is hard, I quickly get tired and move on to something else 😅

I can confirm that the issue _still persists_ on the latest release TOTK Optimizer manager-1.4.3 AppImage.

Moreover, I managed to narrow down the cause of the bug: Workspace Behavior -> Touch Mode settings.

When the desktop is in Touch Mode, window decorations and many other elements such as list items, buttons, system tray icons — everything becomes slightly bigger to accommodate imprecise touch input.

Maybe the framework that this tool builds upon wrongly calculates window size by somehow including window decorations (title/buttons) height and falling back to some hardcoded unusable size? Why does it forcefully disable resize anyway?

![enabled](https://github.com/MaxLastBreath/TOTK-mods/assets/6737986/bd397b78-a02a-4ec6-83e5-5475e0398011)
![disabled](https://github.com/MaxLastBreath/TOTK-mods/assets/6737986/bb8d5f9e-9e9c-4ffd-bba8-caa6e6000ad7)


---

> Ive already written a framework to work with tk, tk isnt the best, but ive already spent a large amount of time making it work

by the way, sounds like a "sunk cost fallacy" 🙃
