### ISSUE TITLE
I need help to get it setup i can't dump things off my switch anymore

### ISSUE THREAD

**Issue by Lchaxlover** [MaxLastBreath/TOTK-mods#144]
I need this mod but when I was downloading it someone was helping me. At the end they told me to dump update files off of my switch to use the mod. I can't do this. Do to reasons I'm not going to discuss because its a long story, I can no longer dump or hack my switch. What do I do? And If I can't download this one is there any other mods you recommend?

**Comment by MaxLastBreath** [comment]
You won't get help with piracy here.
