### ISSUE TITLE
Applying mods doesn't work.

### ISSUE THREAD

**Issue by Elo-gaming** [MaxLastBreath/TOTK-mods#15]
Whenever i apply mods, the box appears, but never progresses 

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/36326354/c0349894-4407-43d9-89ea-17b7da606d4f)

**Comment by MaxLastBreath** [comment]
Can you send the logger file? Are you potentially on a Linux system or are you using the Ryujinx version?

**Comment by MaxLastBreath** [comment]
Fixed, the user had a previous version of PS4 mod selected which threw back the error. If you are facing this issue just reselect the mods :)
