### ISSUE TITLE
TOTK now only shows a black screen

### ISSUE THREAD

**Issue by GMan918** [MaxLastBreath/TOTK-mods#154]
TOTK will not start. the game launches it, but I'm just stuck on a black screen. no menu at all. Anyone have a fix?

I'm running it on Windows 11 and my emulator is Suyu.

**Comment by MaxLastBreath** [comment]
Please check here : [TOTK Optimizer Wiki](https://github.com/MaxLastBreath/TOTK-mods/wiki/TOTK-OPTIMIZER-WIKI)

**Comment by raffa0001** [comment]
I'm on Suyu, i did some tests, it's the depth of field removal causing that, i turned it off and it works fine on 1.0, haven't tested on 1.21 yet

**Comment by MaxLastBreath** [comment]
> I'm on Suyu, i did some tests, it's the depth of field removal causing that, i turned it off and it works fine on 1.0, haven't tested on 1.21 yet, currently i'm testing other options as there seems to be something breaking the world textures from displaying when looking north east

V1.0 isn't really supported so it's very likely some things won't work properly.

the thing breaking textures is the "EXPERIMENTAL" render distance.

**Comment by raffa0001** [comment]
Yeah i just installed the update 1.21, it kind worked until trying to teleport, that's when the game broke, i'll retry the same suspected functions on this version and see if it runs correctly

**Comment by FreiherrSeymore** [comment]
Same here on 1.21. Depth of Field doesnt change anything sadly

**Comment by MaxLastBreath** [comment]
This issue primarily happens on Suyu or Sudachi due to the way they handle keys and stuff. Closing for now as, I can't really do anything about it.
