### ISSUE TITLE
how can i switch my rom file? 

### ISSUE THREAD

**Issue by AleyzRo** [MaxLastBreath/TOTK-mods#156]
**Is your feature request related to a problem? Please describe.**
I got a new Rom version of the game and want to change my rom

**Describe the solution you'd like**
a answer how i can change my rom / feature

**Comment by MaxLastBreath** [comment]
You can't switch your rom file, you'll have to buy the game in a different format altogether. I.e if u have digital copy, you'll need the physical copy or vise versa.
