### ISSUE TITLE
[Flatpak Ryujinx] I don't get it

### ISSUE THREAD

**Issue by ratijas** [MaxLastBreath/TOTK-mods#157]
IIUC this tool is supposed to modify the settings of Yuzu and Ryujinx emulators with optimal settings for TOTK. The UI does not reflect very clearly though. The buttons on top are "SELECT EXECUTABLE" (what do you mean .exe?  you want and ELF executable or a .desktop file?  As a user on Linux I may not know where they are located), "Browse" (Please select Legacy.Appimage -- sorry I'm running Flatpak) , "Use Appdata" (on Linux?). The later seemingly doesn't even do anything on click. What is going on here? How do I configure my Ryujinx Flatpak instance?

The checkboxes (I assume?) in the second column: they have two states, green and white. Which one is checked? Also they are all overlapping their text labels.

The "Switch to Ryujinx" button hides portion of the UI, but it's not clear in which state are we?  The button does not update to "Switch to Yuzu" or anything. It just hides some buttons on every second click. Should they be hidden for Ryujinx? Should they be shown for Ryujinx? I don't know. All the buttons have tooltips with text "None" -- an omission of `str()` from Python language?

Settings page looks like this, and thanks to the shadows effect it is somewhat readable: 
![image](https://github.com/user-attachments/assets/aed844d5-7599-420a-955b-5f558a4e20b9)

**Comment by MaxLastBreath** [comment]
actually the app prioritizes the flatpaks so just pressing apply in the main UI, it should already modify Ryujinx and apply the mod to it too.
