### ISSUE TITLE
[Bug]: stuck in

### ISSUE THREAD

**Issue by IvanPinesLol** [MaxLastBreath/TOTK-mods#159]
### Describe the bug

```bash
loaded Failed to fetch list and dict of zip files. continues... Succesfully loaded api.json.

that's what it said and it's just stuck there, I saw another user reporting this bug and you guys advised him to update the optimizer, but for me it is the latest version: 2.0.9
```

### Reproduction steps

```bash
I didn't have a problem with this until I did, I really don't know how, maybe because I switched from Suyu to Yuzu half way and ran it.
```

### Additional context

```bash
Im using the latest archive of Yuzu (not Suyu) which is the early access 4176, had the optimizer's exe in my downloads folder if that helps
```

### What's your operating system?

Windows 10

**Comment by IvanPinesLol** [comment]
wait nvm it works now but prob took like 5 mins to load in, another problem arised which is applying the patch, now it's stuck at downloading ultracam

**Comment by IvanPinesLol** [comment]
hold up, it's done now, oh so it just took a really long time. Mb sorry for bothering you guys

**Comment by MaxLastBreath** [comment]
Interesting, should be mostly gone as an issue in 3.0, probably slow internet connection?
