### ISSUE TITLE
[Bug]: MacOS - Crash at startup on Ryujinx

### ISSUE THREAD

**Issue by Foul-Tarnished** [MaxLastBreath/TOTK-mods#161]
### Describe the bug

```bash
Ryujinx crash at startup when using Ultracam
```

### Reproduction steps

```bash
- Install Ryujinx on MacOS Sonoma
- Get TOTK
- Add Ultracam at 1080p, 1024x shadows
- Run the game
```

### Additional context

```bash
I tried JIT and hypervisor, no difference
The game work fine without this mod
```

### What's your operating system?

Other

**Comment by Foul-Tarnished** [comment]
[Ryujinx_1.1.1376_2024-08-18_19-37-10.log](https://github.com/user-attachments/files/16650688/Ryujinx_1.1.1376_2024-08-18_19-37-10.log)
`00:00:20.872 |E| .NET TP Worker [mvk-info] Created 3 swapchain images with initial size (3456, 1962) and contents scale 2.0 for screen Built-in Retina Display.`

This is a Macbook Pro M3 (3456x2234p 16:10 display) running Sonoma 14.5

**Comment by MaxLastBreath** [comment]
the crash log you sent wasn't caused by UltraCam or TOTK Optimizer, most likely something else internally in Ryujinx.
