### ISSUE TITLE
[Bug]: No option to select aspect ratio

### ISSUE THREAD

**Issue by FruitJuice** [MaxLastBreath/TOTK-mods#162]
### Describe the bug

```bash
1.Download
2.Open
3.No Aspect ratio option

Image
https://i.imgur.com/EdspR44.png
```

### Reproduction steps

```bash
1.Open TOTK Optimizer
2.No aspect ratio option
```

### Additional context

```bash
1.
2.
3.
...
```

### What's your operating system?

Windows 11

**Comment by FruitJuice** [comment]
![image](https://github.com/user-attachments/assets/0ed73dc6-243e-4210-95fe-442a983de032)

**Comment by MaxLastBreath** [comment]
> ![image](https://private-user-images.githubusercontent.com/22107376/361243304-0ed73dc6-243e-4210-95fe-442a983de032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDc2NjYsIm5iZiI6MTcyNDYwNzM2NiwicGF0aCI6Ii8yMjEwNzM3Ni8zNjEyNDMzMDQtMGVkNzNkYzYtMjQzZS00MjEwLTk1ZmUtNDQyYTk4M2RlMDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE3MzYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YmU2OGY3NmYwNTYwODQzNjBhYzI2MzA4ZWI4ODZhNjNiZWU0MjcxZTdkZjY3NDcwZmUyNjFmNDY3ZTdkY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UOumZD49Ja6OE5Gf6rlLdtLhIijCG2ddwnGxeIEd9V0)

Aspect ratios have been removed for over a month now, due to Nintendo DMCAing romfs mods. They won't be back until a better solution in-engine has been created.
