### ISSUE TITLE
[Bug]: game bugged when changing weapon in depth cave

### ISSUE THREAD

**Issue by goldezz911** [MaxLastBreath/TOTK-mods#173]
### Describe the bug

```bash
bugged
```

### Reproduction steps

```bash
change weapon or item with d pad in depth cave
```

### Additional context

```bash
pls fix it. wish i can show screenshot
```

### What's your operating system?

Windows 11

**Comment by goldezz911** [comment]
![game is bugged](https://github.com/user-attachments/assets/a4b15e8f-422d-45ef-8c0c-742b3aff9c05)

**Comment by MaxLastBreath** [comment]
Issue from your emulator, yuzu/suyu/sudachi etc. I can't fix it, use Ryujinx if it bothers you.
