### ISSUE TITLE
[Bug]: Trojan detected

### ISSUE THREAD

**Issue by StjepanKralj** [MaxLastBreath/TOTK-mods#177]
### Describe the bug

```bash
Hi,

The exe file is flagged as a Trojan. I am guessing this is a false positive? Thanks

Trojan.Agent.Win32.3992696
```

### Reproduction steps

```bash
NA
```

### Additional context

```bash
NA
```

### What's your operating system?

Windows 11

**Comment by MaxLastBreath** [comment]
Yes this is a false positive, all the compilation is done by Github actions.

**Comment by StjepanKralj** [comment]
Thanks for the info and for the quick response. Have a nice day.
