### ISSUE TITLE
Suyu Supported?

### ISSUE THREAD

**Issue by nex86** [MaxLastBreath/TOTK-mods#180]
I have the latest version of Suyu, Yuzu and TOTK optimizer installed.
When I write the default config, it writes it for Suyu and applies it.
But when I launch the game, the emulator closes immediately without any message.

It works with Yuzu, but I have to manually copy the patch from suyu into the yuzu mod directory.

**Comment by MaxLastBreath** [comment]
> I have the latest version of Suyu, Yuzu and TOTK optimizer installed. When I write the default config, it writes it for Suyu and applies it. But when I launch the game, the emulator closes immediately without any message.
> 
> It works with Yuzu, but I have to manually copy the patch from suyu into the yuzu mod directory.

Very likely to be an issue from the emulator itself, why even use Suyu it's worse then original Yuzu for TOTK.

**Comment by nex86** [comment]
>why even use Suyu it's worse then original Yuzu for TOTK.

because totk optimizer automatically applies the patch to suyu instead of yuzu even though I have both installed.
