### ISSUE TITLE
[Bug]: I can't get the optimizer to add the mods or cheats to the game

### ISSUE THREAD

**Issue by Samxtr21** [MaxLastBreath/TOTK-mods#182]
### Describe the bug

```bash
So I was able to apply the mods by extracting the folder and then manually applying it, however I can't get it to do it by just pressing apply, which also does not allow me to apply cheats. I mainly just want infinite dura
```

### Reproduction steps

```bash
I am using the update 1.2.1 and Optimizer version 2.1.0
```

### What's your operating system?

Windows 11

**Comment by MaxLastBreath** [comment]
What emulator or are u trying to do it on your switch?

**Comment by Samxtr21** [comment]
> What emulator or are u trying to do it on your switch?

I'm using yuzu vr 1734

**Comment by MaxLastBreath** [comment]
> > What emulator or are u trying to do it on your switch?
> 
> I'm using yuzu vr 1734

Try clicking on browse and find and select your Yuzu exe and then try clicking apply

**Comment by Samxtr21** [comment]
alre

> > > What emulator or are u trying to do it on your switch?
> > 
> > 
> > I'm using yuzu vr 1734
> 
> Try clicking on browse and find and select your Yuzu exe and then try clicking apply

already tried did not seem to work. I don't know if it is important but I'll attach a picture
![image_2024-11-11_015224163](https://github.com/user-attachments/assets/2f60d6ba-fd29-4773-b666-b3c72a79be14)

**Comment by Samxtr21** [comment]
So I found that it does not read the portable folder and instead defaults to suyu on appdata
