### ISSUE TITLE
Fails to apply certain patch

### ISSUE THREAD

**Issue by D-Maxwell** [MaxLastBreath/TOTK-mods#19]
The Optimizer will hang up on Applying NVIDIA Settings, whilst the console reports the following failure :

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/98100481/ddb90588-69a4-4e97-b89d-0079ecdcb758)

These were my settings. Nothing else has been modified, fresh Ryujinx build.

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/98100481/50ac496d-834d-404c-b28b-5e9373a7a8c6)

**Comment by MaxLastBreath** [comment]
just fixed it internally, thank you for the report again, for now setting it to None in Yuzu mode will install the mods normally.
