### ISSUE TITLE
Font not applied on first boot

### ISSUE THREAD

**Issue by D-Maxwell** [MaxLastBreath/TOTK-mods#20]
I suspect the default font, bahnschrift --at least on Windows-- is not applied upon first launch --until the user manually applies the default settings-- because a variable is not set by default. It should read the settings file and set its value accordingly.

A simple solution could be to manually call the function called upon clicking the `Apply` button in the Optimizer Settings sub-window, unless there are any fundamental impossibilities with this idea of course.

**Comment by MaxLastBreath** [comment]
It was applying Bahnschrift Font instead of Bahnschrift, fixed thank you, gonna release with 1.3.3 soon :)
