### ISSUE TITLE
It doesnt install 60fps and other mods

### ISSUE THREAD

**Issue by ravillarreal** [MaxLastBreath/TOTK-mods#21]
I select ultra preset and make changes but only install these mods in my load folder
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/29802906/bd67912e-6365-41ae-af07-4943a68df4ab)

And the gane runs at 30 fps instead of 60
Testing with version 1.3.3
I've run the programa several times, I tried deleting yuzu folder but ir didn't work
Any help?

**Comment by MaxLastBreath** [comment]
are you using TOTK version 1.2.1? DFPS controls fps if ur stuck at 30 fps ur most likely using TOTK version 1.2.1 (which doesn't have support from dFPS 1.5.5)

**Comment by ravillarreal** [comment]
Im using version 1.1.1

**Comment by ravillarreal** [comment]
nvm y deleted again my yuzu folder and make an new install
