### ISSUE TITLE
Error when applying mods

### ISSUE THREAD

**Issue by c-vaughan** [MaxLastBreath/TOTK-mods#22]
I'm using the latest version of this tool with Ryujinx 1.1.1037 and system version 16.1.0.

There are no mods in my mod directory beforehand, and I'm attempting to use the following config:
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/16975328/eaaa5e34-c2a2-46f6-a954-9b0f49194f0f)

Upon applying the mods, the terminal shows me the following message:
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/16975328/35426a94-722b-439e-8cda-ca8228268e96)

After the error, nothing else happens and there is only a single mod in the folder, Black Screen Fix. I'm not sure if it was fully downloaded or not, but there are only two files within.

Did I go wrong somewhere in my setup? I'm not an expert with this stuff by any means.

Thank you in advance.

**Comment by MaxLastBreath** [comment]
Delete the .ini file, someone else had the same problem yesterday. Look for a file named "Mod_Manager.ini"

**Comment by c-vaughan** [comment]
Thank you so much! I apologize for not seeing the previous thread about it.
