### ISSUE TITLE
Running the EXE.... 

### ISSUE THREAD

**Issue by boyooo** [MaxLastBreath/TOTK-mods#23]
Attempting to start Application.
__SystemINFO__
System: Windows
GPU: NVIDIA GeForce RTX 3070
RAM: 34 GB

TIME: 20:34:02,24 - root - INFO: Attempting to create API instructions. Sun Oct  1 20:34:02 2023
TIME: 20:34:03,552 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 20:34:03,552 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 20:34:03,926 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 20:34:03,926 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 20:34:04,304 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 20:34:04,305 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 20:34:04,676 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 20:34:04,676 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 20:34:04,677 - root - INFO: Github Api instructions have been fetched succesfully.
TIME: 20:34:04,677 - root - INFO: Attempting to create api.json.
TIME: 20:34:04,677 - root - INFO: Creating api.json file..
TIME: 20:34:04,678 - root - INFO: Adding API time to config_file. Sun Oct  1 20:34:04 2023.

It's been like this for a hot minute. I tried earlier and let it sit for 10 minutes. Nothing really works...

**Comment by boyooo** [comment]
waited a little longer.... now it works lol

**Comment by MaxLastBreath** [comment]
oh seems to be a problem with Github API throwing off err, prob something happened to github's API, good to know it works now!
