### ISSUE TITLE
Config parser bug in 1.3.3

### ISSUE THREAD

**Issue by Armin-FalDiS** [MaxLastBreath/TOTK-mods#25]
When I try to apply mods, I get the following error:
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/20294274/d8b2243d-1f71-4d0e-bde5-810690e0348d)

Doesn't matter which options I choose. It did work previously but after the game crashed at some point TOTK Optimizer also became problematic. The game runs if I run it without custom configurations but I am not sure why there is no `Updates` in config.
I remove all the files and it still doesn't work.
I believe the config parser is parsing YuZu's config? That could be corrupted because of the crash...

**Comment by MaxLastBreath** [comment]
delete the .ini file within the optimizer directory, it will work. Or set DFPS to latest.

**Comment by MaxLastBreath** [comment]
[Fixed in new release 1.3.4](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.3.4)
