### ISSUE TITLE
Update 1.2.1 is deselected automatically in yuzu

### ISSUE THREAD

**Issue by JaccoR** [MaxLastBreath/TOTK-mods#26]
When i apply the chosen settings with totk optimizer, the update for TOTK itself (1.2.1) is deselected. I think this happens in the disabling old mods step.

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/31140879/354b1eab-78d3-4c19-9e5f-8769f4fd2404)

**Comment by MaxLastBreath** [comment]
Will look into it!

**Comment by MaxLastBreath** [comment]
I'm not able to replicate it on my end, with either update 1.2.0/1.2.1/1.1.2, if you can dive a bit more into how exactly it happened or a way to replicate it, I'll try to fix it for 1.4.2, seems to be a rare occurrence for now though

**Comment by JaccoR** [comment]
I guess it is something with my yuzu installation. I can't replicate it anymore either. Either way, thanks!
