### ISSUE TITLE
problem select an fps

### ISSUE THREAD

**Issue by asp0909** [MaxLastBreath/TOTK-mods#27]
the 30 fps option doesn't work...it force creates 60 fps    .....update 1.2.1 of course

**Comment by MaxLastBreath** [comment]
Part of the patch notes for 1.4.0

"The new upscaling tech is currently locked to 60 FPS, you can use an external fps cap to get 30 fps."

**Comment by MaxLastBreath** [comment]
Fixed in [TOTK Optimizer 1.4.2](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.4.2)
