### ISSUE TITLE
Cannot run the executable on Windows 11 23H2

### ISSUE THREAD

**Issue by xorpix** [MaxLastBreath/TOTK-mods#29]
Hello. Ran into a problem when trying to run the app.
It crashes before launching with the next exception: 
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/22274805/a904c5e5-57e0-431a-b99c-5d28e7575ead)

**Comment by MaxLastBreath** [comment]
It's a problem with tkkbootstrap but i can try to fix it since i have a custom ttkbootstrap repo.

**Comment by MaxLastBreath** [comment]
Please give this a try https://github.com/MaxLastBreath/TOTK-mods/releases/tag/Test
It has some features that are new and not working, not yet released. But check if it launches now.

**Comment by MaxLastBreath** [comment]
someone on discord said this fixed it for them.
https://stackoverflow.com/questions/14547631/python-locale-error-unsupported-locale-setting

**Comment by MaxLastBreath** [comment]
Fixed in [TOTK Optimizer 1.4.2](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.4.2)
