### ISSUE TITLE
4.1.1 hangs on 1.1.0

### ISSUE THREAD

**Issue by iCanuck** [MaxLastBreath/TOTK-mods#3]
4.1.1 wont load a save files stops quarter way on 1.1.0. even with fresh install, using known working save, and clearing shader cache

**Comment by iCanuck** [comment]
Fixed in 4.1.2

**Comment by MaxLastBreath** [comment]
Yep sorry about that, fixed it as soon as it got reported on discord :)

**Comment by MaxLastBreath** [comment]
Fixed
