### ISSUE TITLE
Locale error on Steam Deck when desktop mode locale not set to en_US

### ISSUE THREAD

**Issue by denniskrq** [MaxLastBreath/TOTK-mods#30]
I'm in Canada and I believe my Steam Deck might've shipped with en_CA.UTF-8 locale by default for its desktop Linux. When I double-click the AppImage to run it the process crashes silently with no apparent cause. If I run the AppImage from terminal I see Python error "unsupported locale setting".  

I can work around this in two ways:

1. Non-permanent solution (needs to be applied for every new terminal window, and the app must be launched from a terminal): run `EXPORT LC_ALL="en_US.UTF-8"` and `export LC_CTYPE="en_US.UTF-8"` before launching the app from CLI
2. Permanent solution: reconfigure OS with en_US.UTF-8 locale

My question is that whether this error can be avoided in code somehow? In theory this could cause issue when the OS is set to anything other than en_US locale

**Comment by MaxLastBreath** [comment]
I have a FIX ready but im not sure if it will work, if u are willing to give it a try i can compile an executable for you.

**Comment by MaxLastBreath** [comment]
If you can please give this a try

https://github.com/MaxLastBreath/TOTK-mods/releases/tag/Locale-FIX

**Comment by denniskrq** [comment]
Just tested the new build, I now see the message `Failed to set Locale unsupported locale setting` in my terminal while the app is loading, but it launches and behaves as expected

**Comment by MaxLastBreath** [comment]
Yeah that's within expectation, it's an error that i added and then set the locale to a correct one manually. Glad it's working, pushing 1.4.2 now.
