### ISSUE TITLE
Ryujinx failed to load config

### ISSUE THREAD

**Issue by hpengyuan** [MaxLastBreath/TOTK-mods#31]
New issue when updated from 1.33 to 1.41. Ryujinx failed to load config.json and loaded default instead. 
Failed config.json post TOTKoptimizer mod attached.
[Config.json](https://github.com/MaxLastBreath/TOTK-mods/files/13078589/Config.json)

Thank you for developing this wonderful mod!

> **00:00:00.030 |W| Application : Failed to load config! Loading the default config instead.
Failed config location C:\Users\hpeng\AppData\Roaming\Ryujinx\Config.json**
00:00:00.030 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1062
00:00:00.032 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.032 |N| Application Print: CPU: 13th Gen Intel(R) Core(TM) i7-13700K ; 24 logical
00:00:00.033 |N| Application Print: RAM: Total 32509 MiB ; Available 25045 MiB
00:00:00.034 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.034 |N| Application PrintSystemInfo: Launch Mode: UserProfile
**00:00:00.319 |W| Application ApplyTheme: The "custom_theme_path" section in "Config.json" contains an invalid path: "Ryujinx.Common.ReactiveObject`1[System.String]".**
00:00:02.154 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
>

**Comment by MaxLastBreath** [comment]
I'll look into it and fix it for 1.4.2, thank you for the report

**Comment by MaxLastBreath** [comment]
Fixed internally, gonna push the fix with 1.4.2 soon(1-2 days?).

**Comment by MaxLastBreath** [comment]
Fixed in [TOTK Optimizer 1.4.2](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.4.2)

**Comment by hpengyuan** [comment]
@MaxLastBreath Reapply appreciate the super fast update! There seems to be a new bug in 1.4.2. I opened a new issue since likely not relevant to this one.
