### ISSUE TITLE
Optimiser stuck at applying the changes

### ISSUE THREAD

**Issue by hpengyuan** [MaxLastBreath/TOTK-mods#32]
New in 1.4.2. The optimizer seems stuck when displaying "applying changes" with the below logs.

> Succesfully loaded api.json.
Detected a Windows based SYSTEM!
Checking for Updates!
No Updates Found. Your app is up to date.
Starting TASKs for Normal Patch..
Exception in thread Thread-1 (run_tasks):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "form.py", line 944, in run_tasks
  File "form.py", line 1329, in Exe_Running
  File "modules\launch.py", line 8, in is_process_running
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

**Comment by MaxLastBreath** [comment]
Will fix it in a few hours, ty.

**Comment by MaxLastBreath** [comment]
pushed an update that fixes it [Hotfix 1.4.3](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.4.3)

**Comment by spzjulien** [comment]
> pushed an update that fixes it [Hotfix 1.4.3](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.4.3)

i can launch 1.4.2 on my ubuntu but 1.4.3 wont launch :(
