### ISSUE TITLE
i can launch 1.4.2 on my ubuntu but 1.4.3 wont launch :(

### ISSUE THREAD

**Issue by spzjulien** [MaxLastBreath/TOTK-mods#33]
hi 
i can launch 1.4.2 on my ubuntu but 1.4.3 wont launch :(
anyway thanks for great work

**Comment by spzjulien** [comment]
seem working now

**Comment by n3arkecv** [comment]
just like this but its on windows
![螢幕擷取畫面 2023-10-24 222035](https://github.com/MaxLastBreath/TOTK-mods/assets/104972675/ee7376a7-6299-449c-87e3-66277f1b3eef)

**Comment by MaxLastBreath** [comment]
[FIxed here](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.4.3) 1.4.3 has been re-released. Sorry about that. Gonna keep this thread incase someone else sees this.

**Comment by spzjulien** [comment]
> Re-releasing 1.4.3, my bad i mistyped something

1.4.3 booting now ! testing it now

**Comment by MaxLastBreath** [comment]
If you face any other issues, let me know! I will fix them as usual and thank you :).

**Comment by spzjulien** [comment]
> If you face any other issues, let me know! I will fix them as usual and thank you :).

seem all good for me, all tested

**Comment by MaxLastBreath** [comment]
Closing this since its been over a day! Longer then the broken 1.4.3 was out for.
