### ISSUE TITLE
Your Tools is fantastic !

### ISSUE THREAD

**Issue by Snipy44** [MaxLastBreath/TOTK-mods#37]
Your Tools is fantastic ! But is possible to have this also for BOTW Yuzu/Ryujinx ? <3

**Comment by MaxLastBreath** [comment]
Thank you! Sadly BOTW doesn't have that many mods for Yuzu/Ryujinx that are essential as most of the botw mods are in CEMU And already mostly built in :(

**Comment by MaxLastBreath** [comment]
Would take too long time, porting every single mod, you should try cemu for botw, it runs twice as better as on yuzu and ryujinx.

**Comment by Snipy44** [comment]
yes i know, and i have this, but i want play on switch emulator ^^'

**Comment by MaxLastBreath** [comment]
Duplicate of #96
