### ISSUE TITLE
Crash when open executable

### ISSUE THREAD

**Issue by viniciusaraujo093** [MaxLastBreath/TOTK-mods#39]
On start application(v1.4.3) app crashes and return this exception error: 
I'm using Yuzu EA 3976

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/57771177/d70d0761-93e4-4968-96bd-0929a1edfd6f)

This is my qt-config.ini
[qt-config.zip](https://github.com/MaxLastBreath/TOTK-mods/files/13384540/qt-config.zip)

**Comment by MaxLastBreath** [comment]
Issue from EA versions, avoid using if possible. Recommend sticking to mainline.

**Comment by t895** [comment]
Sorry about that! Just disabled the unnecessary BOM in my config change and it'll be pushed out soon.
It'll automatically remove that upon launching with the next version.

**Comment by MaxLastBreath** [comment]
> Sorry about that! Just disabled the unnecessary BOM in my config change and it'll be pushed out soon. It'll automatically remove that upon launching with the next version.

Thank you again, I appreciate it.
