### ISSUE TITLE
Error with latest v1.1.1

### ISSUE THREAD

**Issue by Remonli** [MaxLastBreath/TOTK-mods#4]
Hi, got error with latest v1.1.1 on win10 x64 ent 19045:

```
Exception in thread Thread-2 (run_tasks):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "form.py", line 734, in run_tasks
  File "form.py", line 1006, in DownloadFP
  File "modules\qt_config.py", line 146, in modify_disabled_key
  File "modules\qt_config.py", line 113, in add_entry
  File "modules\qt_config.py", line 15, in find_folder_index_by_name
  File "modules\qt_config.py", line 8, in list_all_folders
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\xxx\\AppData\\Roaming\\yuzu\\load\\0100F2C0115B6000'
```

**Comment by MaxLastBreath** [comment]
Hey thank you for the report, do you by any chance have a yuzu folder with a user folder inside?

**Comment by Remonli** [comment]
No , it's not my Yuzu folder, but it still should create one and write mods and confs like previous v1.0.3

**Comment by Lushkin-Aleksandr** [comment]
Hi,
Have the same issue.
`FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\LENOVO\\AppData\\Roaming\\yuzu\\load\\0100F2C0115B6000'`
Perhaps problem is double slashes in the path

**Comment by MaxLastBreath** [comment]
Hi thank you guys again, yeah the double slashes is how the path is stored in the qt-config, there`s a function inside of the script that ensures the path is normalized before its being used, perhaps it`s not as consistent anymore. I will definitely take a look at it, any of you willing to try a test build?

**Comment by Lushkin-Aleksandr** [comment]
Yes. Let me know when I can try it.

**Comment by MaxLastBreath** [comment]
Please give this a try and let me know if the error persists! :) Added a small change to ensure the directory exists.
[TOTK_MOD_Manager.zip](https://github.com/MaxLastBreath/TOTK-mods/files/12206763/TOTK_MOD_Manager.zip)

**Comment by Lushkin-Aleksandr** [comment]
It works fine now) Thanks a lot!

`No Updates Found. Your app is up to date.
Detected a Windows based SYSTEM!
User Folder not Found defaulting to Default Dir!
Disabled
copied file: C:\Users\LENOVO\AppData\Roaming\yuzu\load\0100F2C0115B6000\BlackscreenFix\romfs\UI\LayoutArchive\Common.Product.100.Nin_NX_NVN.blarc.zs
copied file: C:\Users\LENOVO\AppData\Roaming\yuzu\load\0100F2C0115B6000\BlackscreenFix\romfs\UI\LayoutArchive\Common.Product.110.Nin_NX_NVN.blarc.zs
Successfully updated config!
Checking for updates
Downloaded file: C:\Users\LENOVO\AppData\Roaming\yuzu\load\0100F2C0115B6000\DFPS\exefs\main.npdm
Checking for updates
Downloaded file: C:\Users\LENOVO\AppData\Roaming\yuzu\load\0100F2C0115B6000\DFPS\exefs\subsdk9
Nvidia
C:\Users\LENOVO\AppData\Roaming\yuzu\load\0100F2C0115B6000
Installing Nvidia Yuzu Preset
Successfully Installed TOTK Yuzu preset settings!
C:\Users\LENOVO\AppData\Roaming\yuzu\config\qt-config.ini\../custom/0100F2C0115B6000.ini
`

**Comment by MaxLastBreath** [comment]
Thank you, please report any further issues :)
