### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by BrentRosen** [MaxLastBreath/TOTK-mods#40]
I really like the use of your tool on my windows PC but I also have the game running on my Mac. Is there anyway to make the tool MACOS Compatible?

**Comment by MaxLastBreath** [comment]
I don't own a Mac, essentially making it Impossible for me to port it to Mac :( Also Yuzu as well shouldn't work on Mac.

**Comment by mccadi** [comment]
Ah OK, some of us have yuzu running on android + only own a Mac.

**Comment by mv-stns** [comment]
How about Ryujinx? is there a way to manually install the mods?

**Comment by alvindimas05** [comment]
> I really like the use of your tool on my windows PC but I also have the game running on my Mac. Is there anyway to make the tool MACOS Compatible?

Hello, if you are still active, you might want to try this version
https://github.com/alvindimas05/TOTK-mods/actions/runs/9820998956

**Comment by MaxLastBreath** [comment]
Thanks to @alvindimas05 we now have MacOS support :)
