### ISSUE TITLE
60 fps not working on version 1.2.1

### ISSUE THREAD

**Issue by LDCanetti** [MaxLastBreath/TOTK-mods#41]
The app says is fully compatible with v1.2.1 but it is not, only runs at 30 fps max. I've tried to find a compatible mod but no luck so far, latest dynamic FPS version i've found its 1.5.5 beta 3 and doesn't work with 1.2.1 either.

**Comment by MaxLastBreath** [comment]
You need to select upscaling to "NEW" not legacy, legacy won't work for version 1.2.1 as it is also mentioned if you hover over the upscaling option.
