### ISSUE TITLE
Ryujinx Avalonia UI support

### ISSUE THREAD

**Issue by restplz** [MaxLastBreath/TOTK-mods#45]
Would this fix be possible?
The app currently only accepts "ryujinx.exe" when clicking Launch Game, and the Avalonia UI exe has a different name.
Currently the error goes by 
```
NotADirectoryError: [WinError 267] The directory name is invalid: 'D:/(username)/Saved Games/Emulation/Switch/A (MAIN) Emulators & Tools/Ryujinx (Ava UI)/publish/Ryujinx.Ava.exe'
```

**Comment by MaxLastBreath** [comment]
I will add an exception to it in the new update either today or tomorrow :)

**Comment by MaxLastBreath** [comment]
should be fixed! :)
