### ISSUE TITLE
Window size too small on Linux

### ISSUE THREAD

**Issue by c10l** [MaxLastBreath/TOTK-mods#46]
Latest release, 1.4.3. Despite of what the launch logs show, this is not a Steam Deck. It's a Debian desktop machine.

This seems to be a regression of https://github.com/MaxLastBreath/TOTK-mods/issues/14

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/399431/c8fbdfc6-5f49-4475-8add-4ccb49a5ead4)

**Comment by MaxLastBreath** [comment]
Try Workspace Behavior -> Touch Mode settings toggle

**Comment by c10l** [comment]
Thanks, I followed through that whole issue and tried the suggested workarounds to no avail. I can get some screenshots later but it really didn't help.

**Comment by c10l** [comment]
Touch Mode set to auto:

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/399431/8c95a647-6c59-4765-8246-d557f060b63a)

Touch Mode set to enabled:

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/399431/4e02a18a-faad-4750-95a9-6fbb3b890841)

Touch Mode set to disabled:

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/399431/02679083-79a8-478c-b64f-d5a333050315)

**Comment by MaxLastBreath** [comment]
very weird, the only issue is i have no idea how to replicate it as I can't seem to make it trigger on my own, neither on steamdeck or linux

**Comment by MaxLastBreath** [comment]
Hello can you try this? 

Make a file named Manager_Config.ini and paste this inside.

[Settings]
font = Bahnschrift
color = white
shadow_color = light-orange
active_color = cyan
style = flatly
scale = Off
backup = Off
cheat-backup = Off
animation = On

**Comment by c10l** [comment]
It changed but the actual window size is still tiny.

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/399431/67b219bd-2717-4d52-92b1-b4489c98f595)

Is there a way to make the window resizeable? I wouldn't mind having to manually resize it each time, it's better than not being able to use it! :smile:

**Comment by MaxLastBreath** [comment]
Do you mind giving some tests a try, i want to fix it once and for all :D, let me see.

**Comment by MaxLastBreath** [comment]
Can you give version 1.1.0 a try and see if it has this Issue? https://github.com/MaxLastBreath/TOTK-mods/releases/download/manager-1.1.0/TOTK.MOD.Manager.exe

this is before all the scaling stuff being implemented

**Comment by c10l** [comment]
That one crashes. :)

```
$ ./TOTK.Mod.Manager.AppImage 
Checking for Updates!
Detected a steamdeck!
Detected a Linux based SYSTEM!
Error occurred while fetching or parsing Version.json: Expecting property name enclosed in double quotes: line 11 column 3 (char 632)
Traceback (most recent call last):
  File "run.py", line 9, in <module>
  File "form.py", line 148, in __init__
IndexError: list index out of range
[22758] Failed to execute script 'run' due to unhandled exception!
```

**Comment by MaxLastBreath** [comment]
what  about this one?
https://github.com/MaxLastBreath/TOTK-mods/releases/download/manager-1.1.3/TOTK.Mod.Manager.1.1.3.AppImage

**Comment by MaxLastBreath** [comment]
Oh, can you change the config file again to 

[Settings]
font = Bahnschrift
color = white
shadow_color = light-orange
active_color = cyan
style = flatly
scale = 1.0x
backup = Off
cheat-backup = Off
animation = On

**Comment by c10l** [comment]
Same on 1.1.3:

```
gaming@nzxt:~/Downloads/1.1.3$ cat Manager_Config.ini 
[Settings]
font = Bahnschrift
color = white
shadow_color = light-orange
active_color = cyan
style = flatly
scale = 1.0x
backup = Off
cheat-backup = Off
animation = On
gaming@nzxt:~/Downloads/1.1.3$ ./TOTK.Mod.Manager.1.1.3.AppImage 
Checking for Updates!
Detected a steamdeck!
Detected a Linux based SYSTEM!
Error occurred while fetching or parsing Version.json: Expecting property name enclosed in double quotes: line 11 column 3 (char 632)
Traceback (most recent call last):
  File "run.py", line 9, in <module>
  File "form.py", line 149, in __init__
IndexError: list index out of range
[23099] Failed to execute script 'run' due to unhandled exception!
```

And on 1.1.0:

```
gaming@nzxt:~/Downloads/1.1.0$ cat Manager_Config.ini 
[Settings]
font = Bahnschrift
color = white
shadow_color = light-orange
active_color = cyan
style = flatly
scale = 1.0x
backup = Off
cheat-backup = Off
animation = On
gaming@nzxt:~/Downloads/1.1.0$ ./TOTK.Mod.Manager.AppImage 
Checking for Updates!
Detected a steamdeck!
Detected a Linux based SYSTEM!
Error occurred while fetching or parsing Version.json: Expecting property name enclosed in double quotes: line 11 column 3 (char 632)
Traceback (most recent call last):
  File "run.py", line 9, in <module>
  File "form.py", line 148, in __init__
IndexError: list index out of range
[23234] Failed to execute script 'run' due to unhandled exception!
```

**Comment by MaxLastBreath** [comment]
try the latest 1.4.3 with the config change i sent you, let's see how that goes

**Comment by c10l** [comment]
That setting only seems to affect the widgets in the app but the actual window size remains unchanged.

1.0x:

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/399431/5394cb2f-be3e-49ba-a4e5-6ca0e76ea1ae)

1.5x:

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/399431/aabd6c12-baec-4bce-96aa-06345eff280c)

2.0x:

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/399431/d1063530-5fec-4f61-9186-ca317ebe2ea3)

**Comment by MaxLastBreath** [comment]
Give me a minute and i will send you a custom build, waiting for it to compile and see if the size is normal on that one

**Comment by MaxLastBreath** [comment]
https://pixeldrain.com/u/DDAeMm5F

Try this one, it's 1.5.0 custom build with size set to absolute 1200x600 without any scaling.

**Comment by c10l** [comment]
Still nope... :(

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/399431/d3c235ac-843f-4c21-8374-6a179afeefcc)

**Comment by MaxLastBreath** [comment]
got an idea hold on :)

**Comment by MaxLastBreath** [comment]
set the minimum size to 1200x600 and also made it resizeable try
https://pixeldrain.com/u/1c2AeKHt

**Comment by c10l** [comment]
Hey, that works!

The window starts out small like the others, but as soon as it renders the widgets it pops out, no need for manual resizing.

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/399431/acd831ba-72a6-4d57-80d8-a3a1bec52c03)

**Comment by MaxLastBreath** [comment]
eyy that's great! thank you for letting me know, let me know if the pop up windows are bugged too so i can apply the same fix to them as well.

**Comment by c10l** [comment]
The first time I applied patches the window popped up fine. Then I changed some stuff and the pop-up came up blank (literally just a white background) and both it and the main window froze. I had to force-kill it.

Here's the full log on the console if it helps:

```
gaming@nzxt:/home/gaming/Downloads/new$ ./TOTK\ Optimizer\ 1.5.0.AppImage 
The GPU was not detected, nothing to be concerned about. list index out of range




Attempting to start Application.
__SystemINFO__
System: Linux
GPU: Undetected
RAM: 31 GB and used 20.8%


Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Detected a steamdeck!
Detected a Linux based SYSTEM!
Checking for Updates!
No Updates Found. Your app is up to date.
Detected a Ryujinx flatpak!
Starting TASKs for Normal Patch..
/bin/sh: 1: tasklist: not found
Couldn`t detect if Ryujinx.exe is running.
Updating values for UltraCam
starting the search for UI folder link.
Selected default Aspect Ratio.
Attempting to download Black Screen Fix
Downloaded: Black Screen Fix
Downloading DFPS: UltraCam
Downloaded DFPS: UltraCam
Ryujinx Doesn't support custom settings as it, doesn't require them.
Saving user choices in Manager_Config.ini
User choices saved in Memory,Attempting to write into file.
Successfully written into log file
Starting Mod Creator.
Do nothing for now.
Tasks have been COMPLETED. Feel free to Launch the game.
Detected a Ryujinx flatpak!
Starting TASKs for Normal Patch..
/bin/sh: 1: tasklist: not found
Couldn`t detect if Ryujinx.exe is running.
Updating values for UltraCam
starting the search for UI folder link.
Attempting to download Aspect Ratio 21-9
Downloaded: Aspect Ratio 21-9
Downloading DFPS: UltraCam
Downloaded DFPS: UltraCam
Ryujinx Doesn't support custom settings as it, doesn't require them.
Saving user choices in Manager_Config.ini
User choices saved in Memory,Attempting to write into file.
Successfully written into log file
Starting Mod Creator.
Do nothing for now.
```

I imagine this is a separate problem. I have to leave now but can get some more troubleshooting later and open a new issue if required.

**Comment by MaxLastBreath** [comment]
A ryujinx issue I'm assuming, yeah gonna have to fix em all :D

**Comment by MaxLastBreath** [comment]
Thank you for the help, 1.5.0 is live now and the issue should be fixed <3 :)

**Comment by c10l** [comment]
Great stuff, thanks! :)
