### ISSUE TITLE
1.5.0 error

### ISSUE THREAD

**Issue by Tolek8** [MaxLastBreath/TOTK-mods#47]
[logger.txt](https://github.com/MaxLastBreath/TOTK-mods/files/13490471/logger.txt)
![20231128170913](https://github.com/MaxLastBreath/TOTK-mods/assets/109871017/b5930508-3b45-4b60-8768-3a0421d07ef9)

**Comment by MaxLastBreath** [comment]
fixed, lmao a single letter error
