### ISSUE TITLE
What the heck is this?

### ISSUE THREAD

**Issue by zqpvr** [MaxLastBreath/TOTK-mods#48]
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/96351311/3b90c031-3162-4a81-9516-2536367da10e)

**Comment by MaxLastBreath** [comment]
are the mods working? Then it's fine.

**Comment by MaxLastBreath** [comment]
the "? what folder

**Comment by MaxLastBreath** [comment]
Fixed
