### ISSUE TITLE
Any vision, just crash

### ISSUE THREAD

**Issue by NilHenard** [MaxLastBreath/TOTK-mods#49]
Can anybody tell me waht to do?
![Screenshot](https://github.com/MaxLastBreath/TOTK-mods/assets/110549905/b6cda6a9-49da-462a-aa64-250431623122)
[logger.txt](https://github.com/MaxLastBreath/TOTK-mods/files/13498639/logger.txt)

**Comment by MaxLastBreath** [comment]
Weird are you on latest mainline?

**Comment by NilHenard** [comment]
> Weird are you on latest mainline?

I find the problem.My Windows language is Chinese and my default unicode is GBK,so I changed it to UTF-8 and now it runs well.

**Comment by MaxLastBreath** [comment]
ah i see makes sense. Sorry for the late reply
