### ISSUE TITLE
Error while Save Config

### ISSUE THREAD

**Issue by Nightbear** [MaxLastBreath/TOTK-mods#5]
Hello,

While I save my config on the latest version (and I tried the version provided in the issue [Error with latest v1.1.1](https://github.com/MaxLastBreath/TOTK-mods/issues/4)), I have this error :
```
Exception in thread Thread-1 (run_tasks):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "form.py", line 740, in run_tasks
  File "form.py", line 977, in DownloadUI
  File "modules\qt_config.py", line 146, in modify_disabled_key
  File "modules\qt_config.py", line 107, in add_entry
  File "modules\qt_config.py", line 27, in find_title_id_index
  File "configparser.py", line 875, in items
  File "configparser.py", line 875, in <listcomp>
  File "configparser.py", line 871, in <lambda>
  File "configparser.py", line 396, in before_get
  File "configparser.py", line 443, in _interpolate_some
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '% Drop Rate'
```
![Screenshot 2023-07-29 181344](https://github.com/MaxLastBreath/TOTK-mods/assets/1189022/cfadcb0e-8d8b-4bbc-8ccd-9ec3e8ada044)

For your information, I have a user folder. Maybe it's related ?

Thanks for your time.

**Comment by MaxLastBreath** [comment]
Hey can you try the test build i sent in here https://github.com/MaxLastBreath/TOTK-mods/issues/4
Let me know if it fixes this particular issue, I'll push 1.1.2. A bit later today if it does

**Comment by MaxLastBreath** [comment]
Oh sorry, i saw that you tried the version i sent, I will look into it again a bit later, cant rn. Ty for reporting the issue.

**Comment by Nightbear** [comment]
> Oh sorry, i saw that you tried the version i sent, I will look into it again a bit later, cant rn. Ty for reporting the issue.

No problem. Let me know if I can help you to debug that.

Have a nice day.

**Comment by MaxLastBreath** [comment]
Please give 1.1.2 a try, I've added more checks to ensure consistency.

**Comment by MaxLastBreath** [comment]
Can you send me your qt-config from appdata>roaming>yuzu>config>qt-config.ini so i can try to replicate the issue locally

**Comment by MaxLastBreath** [comment]
Looking further into this, it seems to be an issue related to some of the disabled mod that have a special case character(s) and configparser doesnt like that, fixing this will require me to have access to one of the qt-config.ini so i can add exceptions and somehow fix it.

**Comment by MaxLastBreath** [comment]
1.1.3 now handles special characters % caused by mods like increase % drop rate.
Thank you for reporting this issue, I would have not caught it otherwise! :)
[Version 1.1.3 Download](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.1.3)

**Comment by Nightbear** [comment]
I confirm it's working with the 1.1.3.
Thanks for the good work.

PS: I had to remove the pipeline cache to avoid a fps problem (~20 fps limit).

**Comment by MaxLastBreath** [comment]
> 

thank you man, if u find any other issues let me know! Really appreciate it, the function itself has so much potential and sorting those issues out will definitely pay off :).
