### ISSUE TITLE
UnicodeDecodeError for Korean Windows users

### ISSUE THREAD

**Issue by dlwlsdn3642** [MaxLastBreath/TOTK-mods#50]
As a Korean, I have experienced this problem a lot.
This problem occurs because when you use "read()" in Python, it follows Windows' default encoding scheme.

The "json.data" data created through this program is UTF-8, but if you try to read it through "read()", an error occurs because it is read in cp949 (Windows' default Korean encoding method).

Users who do not use UTF-8 (non-English Windows) must write the code below to use this program.
However, this is just my way, so I don't know if there is a better way.

````
config_parser.read(self.configdir, encoding="utf-8")
````
Below is the full text of the error
```
Attempting to start Application.
__SystemINFO__
System: Windows
GPU: NVIDIA GeForce GTX 1080
RAM: 32 GB and used 36.7%


Succesfully loaded api.json.
Traceback (most recent call last):
  File "run.py", line 9, in <module>
  File "form.py", line 64, in __init__
  File "form.py", line 654, in load_canvas
  File "form.py", line 93, in create_canvas
  File "modules\checkpath.py", line 115, in checkpath
  File "configparser.py", line 713, in read
  File "configparser.py", line 1036, in _read
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 1765: illegal multibyte sequence
[19548] Failed to execute script 'run' due to unhandled exception!
```

**Comment by MaxLastBreath** [comment]
I'm implement it, thank you :). I didn't know it would help, but now i do. I appreciate it.

**Comment by iUltraDeus** [comment]
Same error for Chinese Windows and EA 4021

Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Detected a Windows based SYSTEM!
qt-config.ini not found, the script will assume default appdata directories, please reopen Yuzu for consistency and make sure TOTK is present..!
Checking for Updates!
No Updates Found. Your app is up to date.
Saving user choices in Manager_Config.ini
User choices saved in Memory,Attempting to write into file.
Successfully written into log file
Successfully selected Yuzu.exe! And a portable folder was found at D:/Games/yuzu-windows-msvc-early-access!
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "form.py", line 995, in select_yuzu_exe
  File "modules\checkpath.py", line 80, in checkpath
  File "configparser.py", line 713, in read
  File "configparser.py", line 1036, in _read
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa0 in position 5361: illegal multibyte sequence

**Comment by MaxLastBreath** [comment]
> Same error for Chinese Windows and EA 4021
> 
> Attemping to fetch list and dict of zip files. Fetch list and dict operation success. Attemping to fetch list and dict of zip files. Fetch list and dict operation success. Attemping to fetch list and dict of zip files. Fetch list and dict operation success. Attemping to fetch list and dict of zip files. Fetch list and dict operation success. Detected a Windows based SYSTEM! qt-config.ini not found, the script will assume default appdata directories, please reopen Yuzu for consistency and make sure TOTK is present..! Checking for Updates! No Updates Found. Your app is up to date. Saving user choices in Manager_Config.ini User choices saved in Memory,Attempting to write into file. Successfully written into log file Successfully selected Yuzu.exe! And a portable folder was found at D:/Games/yuzu-windows-msvc-early-access! Exception in Tkinter callback Traceback (most recent call last): File "tkinter__init__.py", line 1948, in **call** File "form.py", line 995, in select_yuzu_exe File "modules\checkpath.py", line 80, in checkpath File "configparser.py", line 713, in read File "configparser.py", line 1036, in _read UnicodeDecodeError: 'gbk' codec can't decode byte 0xa0 in position 5361: illegal multibyte sequence

can you try to change the resolution to something else or maybe delete the config.ini file

**Comment by huangwjwork** [comment]
log has some different

**Comment by MaxLastBreath** [comment]
[Update 1.5.4](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.5.4) fixes this issue :).

**Comment by yyk725** [comment]
I am also a chinese player and update 1.5.4 just can't fix UnicodeDecodeError. Instead, you can enable "use unicode utf-8 for worldwide language support" to solve it. 

Here is a [tutorial](https://learn.microsoft.com/en-us/answers/questions/587680/where-can-i-find-beta-use-unicode-utf-8-for-worldw) to enable this option.

**Comment by ddm99** [comment]
I was able to fix the above error by changing line 1032 of form.py to 'qtconfig.read(self.configdir, encoding="utf-8")'

**Comment by MaxLastBreath** [comment]
> I was able to fix the above error by changing line 1032 of form.py to 'qtconfig.read(self.configdir, encoding="utf-8")'

Oh! I must have missed that one, feel free to do a pull request
