### ISSUE TITLE
TOTK Optimizer 1.5.3 sets Ryujinx resolution scaling to 2x

### ISSUE THREAD

**Issue by DisBot404** [MaxLastBreath/TOTK-mods#51]
For some reason the most recent release of totk optimizer sets the resolution scaling in Ryujinx to 1440p (2x). Which makes performance really bad (we're talking around 30fps in my case, where it would normally hit close to 60).

**Comment by MaxLastBreath** [comment]
Ah the intention was to run handheld at 2x because better integration for skyisland and stuff

**Comment by MaxLastBreath** [comment]
[Update 1.5.4](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.5.4) fixes this issue :).
