### ISSUE TITLE
Running an EXE and nothing happens.

### ISSUE THREAD

**Issue by killaxkr** [MaxLastBreath/TOTK-mods#53]
Hello there.

When I started your program first time it worked fine for a few times. After that, I tried to move the folder of your program and it doesn't work since then.

I erased the original folder and tried to run a new EXE. Would this have been a mistake? Sadly, I didn't backup the log from the old folder.

Here's the log after I run a new EXE for the first time. 

-----------------------------------------------------------------------------------------------------------------------------

TIME: 10:15:32,747 - LOGGER - INFO: 

Attempting to start Application.
__SystemINFO__
System: Windows
GPU: NVIDIA GeForce RTX 3080 Ti
RAM: 64 GB and used 12.1%

TIME: 10:15:32,747 - root - INFO: Attempting to create API instructions. Sun Dec 10 10:15:32 2023
TIME: 10:15:33,195 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 10:15:33,195 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 10:15:33,620 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 10:15:33,620 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 10:15:34,39 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 10:15:34,40 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 10:15:34,468 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 10:15:34,468 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 10:15:34,469 - root - INFO: Github Api instructions have been fetched succesfully.
TIME: 10:15:34,469 - root - INFO: Attempting to create api.json.
TIME: 10:15:34,469 - root - INFO: Creating api.json file..
TIME: 10:15:34,470 - root - INFO: Adding API time to config_file. Sun Dec 10 10:15:34 2023.
TIME: 10:17:55,365 - LOGGER - INFO: 

-----------------------------------------------------------------------------------------------------------------------------

after this nothing happens and I tried to reopen it.

-----------------------------------------------------------------------------------------------------------------------------

Attempting to start Application.
__SystemINFO__
System: Windows
GPU: NVIDIA GeForce RTX 3080 Ti
RAM: 64 GB and used 9.4%

TIME: 10:17:55,365 - root - INFO: Attempting to load local api.json..
TIME: 10:17:55,365 - root - INFO: Loading api.json file..
TIME: 10:17:55,371 - LOGGER - INFO: Succesfully loaded api.json.
TIME: 10:21:34,647 - LOGGER - INFO: 

-----------------------------------------------------------------------------------------------------------------------------

Nothing happens again. Have I done something wrong? I use both yuzu and ryujinx.

**Comment by killaxkr** [comment]
It was a language issue. I changed the unicode to UTF-8 and now it works fine.

**Comment by MaxLastBreath** [comment]
Ah sorry, i was asleep lol. I'll include some fixes to that on the next release whenever i get on it :-)
