### ISSUE TITLE
AppImage 1.5.3 buttons do nothing

### ISSUE THREAD

**Issue by MG4vQIs7Fv** [MaxLastBreath/TOTK-mods#56]
I'm exited to try out the new mods. Unfortunately I ran into a bit of a problem. The 1.5.3 AppImage buttons (the newer animated ones) don't seem to do anything.

I have entered all my settings and nothing happens when pressing "Apply" or "Launch." When I quit the program and reopen my settings have not been saved either.
The log and console don't show anything happening when I press the buttons.

Except for the "Backup" button, which results in:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1948, in __call__
  File "form.py", line 177, in <lambda>
  File "modules/backup.py", line 12, in backup
FileNotFoundError: [Errno 2] No such file or directory: '"/home/userluser/.local/share/yuzu/nand"/user/save/0000000000000000'
```
The two double quote characters are the problem here. The dir does exist.

Right clicking in the window prints the following to console:
`CRODS = X=443 + Y=425 + .!canvas`

Console output:
```
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Detected a steamdeck!
Detected a Linux based SYSTEM!
Checking for Updates!
No Updates Found. Your app is up to date.
```

The log file:
```
TIME: 18:13:46,876 - root - INFO: Attempting to create API instructions. Thu Dec 14 18:13:46 2023
TIME: 18:13:47,79 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 18:13:47,79 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 18:13:47,273 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 18:13:47,273 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 18:13:47,470 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 18:13:47,470 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 18:13:47,678 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 18:13:47,678 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 18:13:47,680 - root - INFO: Github Api instructions have been fetched succesfully.
TIME: 18:13:47,680 - root - INFO: Attempting to create api.json.
TIME: 18:13:47,680 - root - INFO: Creating api.json file..
TIME: 18:13:47,680 - root - INFO: Adding API time to config_file. Thu Dec 14 18:13:47 2023.
TIME: 18:13:49,254 - LOGGER - INFO: Detected a steamdeck!
TIME: 18:13:49,261 - LOGGER - INFO: Detected a Linux based SYSTEM!
TIME: 18:13:49,370 - LOGGER - INFO: Checking for Updates!
TIME: 18:13:49,564 - LOGGER - INFO: No Updates Found. Your app is up to date.
```

**Comment by MaxLastBreath** [comment]
Ah that issue, inconsistencies in the qt config of yuzu, for some reason it has decided to put your filepath in strings, if you go to "local/.config/yuzu/wt-config.ini" just remove the "" from the filepath from both sides and then apply the mods. I have no idea why it does this, it does it like 1% of the times on LINUX ONLY. Super inconsistent behavior.

**Comment by MG4vQIs7Fv** [comment]
The Backup button now works, however the Apply and Launch buttons still do not. It seems like this issue started with 1.5.0.

What you wrote reminded me of a similar issue I had with 1.4.3 where it could not find the "load" dir and it created the directory structure in the current dir instead.
After removing the quotes from "qt-config.ini" this is no longer the case.

I'll see if I can find some out some more about qt since it might have something to do with it.

**Comment by MaxLastBreath** [comment]
Certainly an issue with the qt-config generation and the launch button was never really configured for Linux, it actually shouldn't even show up like in 1.4.3, but i forgot to disable it

**Comment by MaxLastBreath** [comment]
[Update 1.5.4](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.5.4) fixes this issue :).
