### ISSUE TITLE
Can not find gpu amd 6750gre (The GPU was not detected)

### ISSUE THREAD

**Issue by huangwjwork** [MaxLastBreath/TOTK-mods#57]
My gpu was amd 6750gre，when I  run TOTK.Optimizer.1.5.3.exe , it prompts an error.

logs

TIME: 14:28:31,502 - LOGGER - WARNING: The GPU was not detected, nothing to be concerned about. list index out of range
TIME: 14:28:31,507 - LOGGER - INFO: 

Attempting to start Application.
__SystemINFO__
System: Windows
GPU: Undetected
RAM: 32 GB and used 47.3%

TIME: 14:28:31,507 - root - INFO: Attempting to create API instructions. Sat Dec 16 14:28:31 2023
TIME: 14:28:34,21 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 14:28:34,21 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 14:28:35,639 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 14:28:35,640 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 14:28:38,406 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 14:28:38,407 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 14:28:41,96 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 14:28:41,97 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 14:28:41,98 - root - INFO: Github Api instructions have been fetched succesfully.
TIME: 14:28:41,98 - root - INFO: Attempting to create api.json.
TIME: 14:28:41,99 - root - INFO: Creating api.json file..
TIME: 14:28:41,99 - root - INFO: Adding API time to config_file. Sat Dec 16 14:28:41 2023.
TIME: 14:30:22,524 - LOGGER - WARNING: The GPU was not detected, nothing to be concerned about. list index out of range
TIME: 14:30:22,529 - LOGGER - INFO:

**Comment by MaxLastBreath** [comment]
oh dont worry about this at all, the information is there just for debugging, nothing to be concerned about :)

**Comment by huangwjwork** [comment]
but after cmd window exist ,the ui does not open ，this is nothing.

**Comment by MaxLastBreath** [comment]
Can you send the cmd error? Screenshot it

**Comment by huangwjwork** [comment]
There's nothing; it exits very quickly.

**Comment by huangwjwork** [comment]
could I run this manager by src code, I have python env.

**Comment by huangwjwork** [comment]
I run successful by use the src/run.py ，and the gui is open.

**Comment by MaxLastBreath** [comment]
Oh nice, you probably have the Unicode problem, like the other report, switching language will fix it temporary

**Comment by MaxLastBreath** [comment]
#50

**Comment by huangwjwork** [comment]
![Uploading totk.png…]()

**Comment by huangwjwork** [comment]
![totk](https://github.com/MaxLastBreath/TOTK-mods/assets/29568513/d043cd4e-4bd2-4c45-a4f2-919f73b582db)

**Comment by huangwjwork** [comment]
log has some difference

**Comment by huangwjwork** [comment]
and this is TOTK.Optimizer.1.5.3.exe log

TIME: 16:54:11,540 - LOGGER - WARNING: The GPU was not detected, nothing to be concerned about. list index out of range
TIME: 16:54:11,544 - LOGGER - INFO: 



Attempting to start Application.
__SystemINFO__
System: Windows
GPU: Undetected
RAM: 32 GB and used 47.5%


TIME: 16:54:11,544 - root - INFO: Attempting to create API instructions. Sat Dec 23 16:54:11 2023
TIME: 16:54:12,516 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 16:54:12,516 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 16:54:13,475 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 16:54:13,475 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 16:54:14,455 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 16:54:14,455 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 16:54:15,507 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 16:54:15,507 - LOGGER - INFO: Fetch list and dict operation success.
TIME: 16:54:15,509 - root - INFO: Github Api instructions have been fetched succesfully.
TIME: 16:54:15,509 - root - INFO: Attempting to create api.json.
TIME: 16:54:15,509 - root - INFO: Creating api.json file..
TIME: 16:54:15,510 - root - INFO: Adding API time to config_file. Sat Dec 23 16:54:15 2023.

**Comment by MaxLastBreath** [comment]
download the current version and see if it works now :)

**Comment by huangwjwork** [comment]
which? the src or the exe.

**Comment by MaxLastBreath** [comment]
i just pushed an update to the src code, you can just download it from github itself

**Comment by huangwjwork** [comment]
It's run 
HEAD is now at 8148478 Update Version Number

**Comment by MaxLastBreath** [comment]
[Update 1.5.4](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.5.4) fixes this issue :).

**Comment by huangwjwork** [comment]
ok, it's fixed, thanks
