### ISSUE TITLE
On "Apply" windows is stuck on "Creating patch manager"

### ISSUE THREAD

**Issue by edrin17** [MaxLastBreath/TOTK-mods#58]
Hi,
When I click on apply the pop-up windows shows: Creating Mod ManagerPatch and get stuck.
Here is what I got from the console output:

> Attempting to start Application.
> __SystemINFO__
> System: Linux
> GPU: NVIDIA GeForce RTX 2080 Ti
> RAM: 28 GB and used 9.3%
> 
> Succesfully loaded api.json.
> Detected a Yuzu flatpak!
> Detected a Linux based SYSTEM!
> Checking for Updates!
> No Updates Found. Your app is up to date.
> Detected a Yuzu flatpak!
> Starting TASKs for Normal Patch..
> /bin/sh: 1: tasklist: not found
> Couldn't detect if Yuzu.exe is running.
> Updating values for UltraCam
> starting the search for UI folder link.
> Selected default Aspect Ratio.
> Attempting to download Black Screen Fix
> Black Screen Fix FOLDER already exists, continue...
> Downloading DFPS: UltraCam
> Downloaded DFPS: UltraCam
> Settings selection is None. Returning!
> Saving user choices in Manager_Config.ini
> User choices saved in Memory,Attempting to write into file.
> Successfully written into log file
> Starting Mod Creator.
> Exception in thread Thread-1 (run_tasks):
> Traceback (most recent call last):
>   File "threading.py", line 1038, in _bootstrap_inner
>   File "threading.py", line 975, in run
>   File "form.py", line 1072, in run_tasks
>   File "form.py", line 1227, in Create_Mod_Patch
> ValueError: '1440p QHD - Experimental' is not in list

Maybe I'm doing something wrong...
Anyway, thanks for the work !

**Comment by edrin17** [comment]
I got

**Comment by edrin17** [comment]
"1440p QHD - Experimental" was an old value from the save in the menu that triggered the problem... The menu list need to be refresh in some way I think.
Sorry for that.

**Comment by MaxLastBreath** [comment]
oh no worries, it's just 1.5.0 that changed some things :)
