### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:'

### ISSUE THREAD

**Issue by Volunruud** [MaxLastBreath/TOTK-mods#59]
@
![error](https://github.com/MaxLastBreath/TOTK-mods/assets/48101059/8e4d5d3e-c75f-4f2f-99a6-cf4b9ad2e65b)
I'm able to launch the game via the Launch button but every time i try to apply Display Settings i get the following:

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:'

I noticed i didn't have a yuzu folder in my appdata so i created one and replicated the files into it. I was able to launch it normally from there. I set the location of the exe file to there since i thought it needed to be in the C drive but i'm still getting the same error.

Any idea what i can try to remedy this?

Thanks!

**Comment by MaxLastBreath** [comment]
This is caused by yuzu inconsistently putting it's directory in it's config inside of a string instead of the normal way they write things, it's very odd behavior and very inconsistent

**Comment by MaxLastBreath** [comment]
This should be addressed in latest version btw

**Comment by MaxLastBreath** [comment]
[Update 1.5.4](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.5.4) fixes this issue :).

**Comment by Volunruud** [comment]
I'm still getting it in 1.5.4 :\
