### ISSUE TITLE
Application was running about an hour ago then suddenly after a restart it refuses to open.

### ISSUE THREAD

**Issue by projectp0thi** [MaxLastBreath/TOTK-mods#60]
TIME: 19:24:47,648 - LOGGER - INFO: 

Attempting to start Application.
__SystemINFO__
System: Windows
GPU: NVIDIA GeForce RTX 4070 Ti
RAM: 32 GB and used 24.0%

TIME: 19:24:47,648 - root - INFO: Attempting to create API instructions. Wed Dec 20 19:24:47 2023
TIME: 19:24:47,973 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 19:24:47,973 - LOGGER - ERROR: Failed to fetch list and dict of zip files. continues...
TIME: 19:24:47,974 - root - ERROR: Couldn't find local api.json data,Application will default to stored api.json data.
TIME: 19:24:47,974 - root - INFO: Loading api.json file..
TIME: 19:24:47,974 - root - INFO: api.json file not found, loading internal data.
TIME: 19:24:47,974 - LOGGER - INFO: Succesfully loaded api.json.
TIME: 19:25:08,834 - LOGGER - INFO: 

Attempting to start Application.
__SystemINFO__
System: Windows
GPU: NVIDIA GeForce RTX 4070 Ti
RAM: 32 GB and used 23.7%

TIME: 19:25:08,834 - root - INFO: Attempting to create API instructions. Wed Dec 20 19:25:08 2023
TIME: 19:25:09,177 - LOGGER - INFO: Attemping to fetch list and dict of zip files.
TIME: 19:25:09,177 - LOGGER - ERROR: Failed to fetch list and dict of zip files. continues...
TIME: 19:25:09,178 - root - ERROR: Couldn't find local api.json data,Application will default to stored api.json data.
TIME: 19:25:09,178 - root - INFO: Loading api.json file..
TIME: 19:25:09,178 - root - INFO: api.json file not found, loading internal data.
TIME: 19:25:09,178 - LOGGER - INFO: Succesfully loaded api.json.
<img width="632" alt="test" src="https://github.com/MaxLastBreath/TOTK-mods/assets/127146455/3e7f6214-1821-4175-9b49-c8caa877bb2b">

**Comment by projectp0thi** [comment]
<img width="853" alt="error 1" src="https://github.com/MaxLastBreath/TOTK-mods/assets/127146455/9fe15692-24b2-4f34-aff8-0121eaaf07b1">
 this is not shown in the logger.txt for some reason.

**Comment by n3arkecv** [comment]
me too, Mine is like this
![螢幕擷取畫面 2023-12-23 113727](https://github.com/MaxLastBreath/TOTK-mods/assets/104972675/238b388f-ea90-4d45-9664-73fb0410e57c)

**Comment by MaxLastBreath** [comment]
Ah it's Unicode issues, change your windows language to English usa or the other English languages and it should work, I'll actually patch this next month. Taking a break during holidays :)

**Comment by n3arkecv** [comment]
> Ah it's Unicode issues, change your windows language to English usa or the other English languages and it should work, I'll actually patch this next month. Taking a break during holidays :)

OK Thank you bro for putting so much effort, have a Nice Holiday!

**Comment by MaxLastBreath** [comment]
#57 #50 are the same problems and thank you :)

**Comment by MaxLastBreath** [comment]
[Update 1.5.4](https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.5.4) fixes this issue :).
