### ISSUE TITLE
Motion Control stops working after entering FreeCam once

### ISSUE THREAD

**Issue by Sirulex** [MaxLastBreath/TOTK-mods#61]
I use a DualSense Controller to play TOTK. Everything works fine except motion control for aiming stops working after entering FreeCam (via the UltraCam mod) once. Motion Control starts working again, if the Controller is reconnected physically or logically through Yuzu.

**Comment by MaxLastBreath** [comment]
Oh i see, i think i may have fixed this issue in the beta version but I'm unsure, i don't use motion controls but I'll ask someone who does if it's working properly now.

**Comment by MaxLastBreath** [comment]
Will be fixed in Optimizer 1.6 :)
