### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"C:' with 1.5.4

### ISSUE THREAD

**Issue by Volunruud** [MaxLastBreath/TOTK-mods#64]
Hey there!

I posted about this error and it was stated that it was fixed in 1.5.4, but I'm still getting it :(

<img width="691" alt="image" src="https://github.com/MaxLastBreath/TOTK-mods/assets/48101059/24421aa7-39ce-414a-ac16-30091487076c">

**Comment by MaxLastBreath** [comment]
gonna push a new update soon that addresses this issue entirely.

**Comment by MaxLastBreath** [comment]
Should be Fixed~ in [latest](https://github.com/MaxLastBreath/TOTK-mods/releases/latest)
