### ISSUE TITLE
When I press the APPLY button, no mod file is generated and nothing happens.

### ISSUE THREAD

**Issue by rarikuma** [MaxLastBreath/TOTK-mods#65]
When I press the APPLY button, no mod file is generated and nothing happens.
The version of TOTK Optimizer is 1.5.4.
Terminal displays the following error message.

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "form.py", line 351, in <lambda>
  File "form.py", line 1032, in submit
  File "configparser.py", line 713, in read
  File "configparser.py", line 1036, in _read
UnicodeDecodeError: 'cp932' codec can't decode byte 0x97 in position 3236: illegal multibyte sequence

![D__Applications_x64_TOTKOptimizer_TOTK Optimizer exe 2024_01_03 20_38_42](https://github.com/MaxLastBreath/TOTK-mods/assets/135856005/de84dde4-a508-4c17-b5bd-28eff36e3ba1)

**Comment by MaxLastBreath** [comment]
please use a language with a native utf-8 decoder, i will fix the errors in the next update

**Comment by rarikuma** [comment]
Thanks for the reply. I will wait with anticipation for the next update.

I am not sure what you mean by using a language with native utf-8 decoder, are you referring to the language setting in what?
Another thread (https://github.com/MaxLastBreath/TOTK-mods/issues/60#issuecomment-1868235916) said to change the Windows language to English, so I did that too, but the change I did that, but there was no change and I got the same error message.

**Comment by MsRiaCayde** [comment]
![TOTKOPTISNIP](https://github.com/MaxLastBreath/TOTK-mods/assets/82339009/f8d030a2-e5b0-47ec-9ac3-c521dd9cb45b)
Encountering a similar issues as yours. This was a fresh/first time install of the Optimizer on Win10 with Administrator permissions. Hitting apply brings up the small window but it never loads during the "Creating Mod ManagerPatch" phase. Unsure how to proceed.

**Comment by MaxLastBreath** [comment]
ah your config file is messed up 

> ![TOTKOPTISNIP](https://private-user-images.githubusercontent.com/82339009/294707162-f8d030a2-e5b0-47ec-9ac3-c521dd9cb45b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzAyODksIm5iZiI6MTcwNDU2OTk4OSwicGF0aCI6Ii84MjMzOTAwOS8yOTQ3MDcxNjItZjhkMDMwYTItZTViMC00N2VjLTlhYzMtYzUyMWRkOWNiNDViLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE5Mzk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ZGY1NjgxMmZiMTI1ZDMwNDRkZDA2MjMyOTUwOTEzZmY4MGE5MWI2NDg2ZWVjMTgyY2EwNWZhZWJkZTJjOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uacTPnr2tIOZ0QqCanlEF-B9h2QvizNbIQ3cleccfZ8) Encountering a similar issues as yours. This was a fresh/first time install of the Optimizer on Win10 with Administrator permissions. Hitting apply brings up the small window but it never loads during the "Creating Mod ManagerPatch" phase. Unsure how to proceed.

**Comment by MaxLastBreath** [comment]
About to push a new update soon that addresses this issue entirely as well.

However I can't fix the duplicate err issue, as that's just broken config file from yuzu?

**Comment by MaxLastBreath** [comment]
Should be Fixed~ in [latest](https://github.com/MaxLastBreath/TOTK-mods/releases/latest)

**Comment by rarikuma** [comment]
I updated the TOTK Optimizer version to 1.5.5 and pressed the APPLY button, but it still outputs an error.
![Game Bar Captures 2024_01_25 20_22_21](https://github.com/MaxLastBreath/TOTK-mods/assets/135856005/7cc23b8a-9695-4699-8c3d-c049156a9912)
