### ISSUE TITLE
Buttons don't respond in AppImage 1.5.4

### ISSUE THREAD

**Issue by Scarycrovv** [MaxLastBreath/TOTK-mods#66]
When I click any button nothing happens. No error in the logs, no popup window, it doesn't even open the links from the discord or github buttons.

I get the following log when I start the AppImage:
```
$ ./TOTK.Optimizer.1.5.4.AppImage 




Attempting to start Application.
__SystemINFO__
System: Linux
GPU: NVIDIA GeForce RTX 3080 Ti
RAM: 32 GB and used 9.7%


Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Attemping to fetch list and dict of zip files.
Fetch list and dict operation success.
Detected a steamdeck!
Detected a Yuzu flatpak!
Detected a Linux based SYSTEM!
Checking for Updates!
No Updates Found. Your app is up to date.
```

No idea why it detects my system as steamdeck. I tried an older version (1.5.3) with the exact same result.

I guess it's probably a issue with my system configuration, but I can't see any hint where to look.

**Comment by Scarycrovv** [comment]
I managed to fix the issue for me by running the python code directly and it turned out to be an issue with the image_button implementation.
I changed the button type for the apply button in the form.py file to a regular button like the backup-button and than everything worked.

[form.py](https://github.com/MaxLastBreath/TOTK-mods/blob/803b8064d771b6aaa2f1af7e173bcb9c35086e24/src/form.py#L347)
```
self.on_canvas.create_button(
    master=self.window, canvas=canvas,
    btn_text="apply",
    row=510, cul=25, width=7,
    tags=["Button"],
    description_name="apply",
    command=lambda: self.submit()
)

# self.on_canvas.image_Button(
#     canvas=canvas,
#     row=510, cul=25,
#     img_1=self.apply_element, img_2=self.apply_element_active,
#     command=lambda event: self.submit
# )
```

I'm not sure what the actual problem is and I'm not so deep into the code that I can fully understand the GUI implementation. Therefor I'm just leaving all system and library information here for anyone who wants to try to reproduce the issue or find a better solution.

Here are my system information:
```
System:
  Host: user-desktop Kernel: 6.5.0-14-generic arch: x86_64 bits: 64
    compiler: N/A Desktop: GNOME v: 45.1 Distro: Ubuntu 23.10 (Mantic Minotaur)
Machine:
  Type: Desktop Mobo: Micro-Star model: MPG X570 GAMING EDGE WIFI (MS-7C37)
    v: 1.0 serial: <superuser required> UEFI: American Megatrends LLC. v: 1.N0
    date: 10/13/2023
CPU:
  Info: 8-core model: AMD Ryzen 7 3700X bits: 64 type: MT MCP arch: Zen 2
    rev: 0 cache: L1: 512 KiB L2: 4 MiB L3: 32 MiB
  Speed (MHz): avg: 2395 high: 3600 min/max: 2200/4426 boost: enabled cores:
    1: 2200 2: 2112 3: 2200 4: 2200 5: 2200 6: 2200 7: 2200 8: 3600 9: 2200
    10: 2200 11: 3600 12: 2200 13: 2200 14: 2200 15: 2613 16: 2200
    bogomips: 115194
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA GA102 [GeForce RTX 3080 Ti] driver: nvidia v: 545.29.06
    arch: Ampere bus-ID: 2d:00.0
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 23.2.0 driver: X:
    loaded: modesetting,nouveau,nvidia unloaded: fbdev,vesa
    gpu: nvidia,nvidia-nvswitch resolution: 1: 2560x1440 2: 2560x1440
  API: OpenGL v: 4.6.0 NVIDIA 545.29.06 renderer: NVIDIA GeForce RTX 3080
    Ti/PCIe/SSE2 direct-render: Yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Micro-Star MSI X570-A PRO driver: r8169 v: kernel port: d000
    bus-ID: 27:00.0
  IF: enp39s0 state: up speed: 1000 Mbps duplex: full mac: 00:d8:61:9d:03:f8
  Device-2: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi
    v: kernel bus-ID: 29:00.0
  IF: wlp41s0 state: down mac: 24:ee:9a:51:d6:0a
Drives:
  Local Storage: total: 3.15 TiB used: 1.7 TiB (54.1%)
Info:
  Processes: 380 Uptime: 3h 43m Memory: total: 32 GiB available: 31.25 GiB
  used: 5.18 GiB (16.6%) Init: systemd target: graphical (5) Compilers:
  gcc: 13.2.0 Packages: 2102 Shell: Bash v: 5.2.15 inxi: 3.3.29

```

Python Libs installed via pip or apt-get:
```
Python                  3.11.6
tk                      0.1.0
tk-tools                0.16.0
ttkbootstrap            1.10.1
requests                2.31.0
pip                     23.3.2
psutil                  5.9.7
Pillow                  10.0.0
patool                  2.0.0
packaging               23.2
GPUtil                  1.4.0
screeninfo              0.8.1

idle3/mantic,mantic,now 3.11.4-5 all
python3-pil.imagetk/mantic,now 10.0.0-1 amd64
```

**Comment by MaxLastBreath** [comment]
afaik, we talked about this in discord. This seems to be pretty rare issue that I can't replicate rn

**Comment by 3rgoProxy** [comment]
> I have an easier workaround, for me the Apply button would highlight but I could not press it nor the Github or Donate button.
> 
> I could press the button by doing: `Shift + Left Click`
> 
> That is it, after that the terminal shows the patches and configuration applying. Hope this helps.
> 
> Edit: left is this hand and right the other one.

You are an absolute chad! Thanks that solved the issue for me as well! I was so confused as to why this was happening. I wonder if it has anything to do with using a tiling window manager as opposed to a DE?

**Comment by MaxLastBreath** [comment]
> > I have an easier workaround, for me the Apply button would highlight but I could not press it nor the Github or Donate button.
> > I could press the button by doing: `Shift + Left Click`
> > That is it, after that the terminal shows the patches and configuration applying. Hope this helps.
> > Edit: left is this hand and right the other one.
> 
> You are an absolute chad! Thanks that solved the issue for me as well! I was so confused as to why this was happening. I wonder if it has anything to do with using a tiling window manager as opposed to a DE?

Is this still happening on 2.0.5? It should've been fixed, i forgot to mention it in the patch notes 😅

**Comment by 3rgoProxy** [comment]
> > > I have an easier workaround, for me the Apply button would highlight but I could not press it nor the Github or Donate button.
> > > I could press the button by doing: `Shift + Left Click`
> > > That is it, after that the terminal shows the patches and configuration applying. Hope this helps.
> > > Edit: left is this hand and right the other one.
> > 
> > 
> > You are an absolute chad! Thanks that solved the issue for me as well! I was so confused as to why this was happening. I wonder if it has anything to do with using a tiling window manager as opposed to a DE?
> 
> Is this still happening on 2.0.5? It should've been fixed, i forgot to mention it in the patch notes 😅

It is still happening to me. Not sure what is causing it though, although I suspect is might be something to do with my window manager.

**Comment by MaxLastBreath** [comment]
> > > > I have an easier workaround, for me the Apply button would highlight but I could not press it nor the Github or Donate button.
> > > > I could press the button by doing: `Shift + Left Click`
> > > > That is it, after that the terminal shows the patches and configuration applying. Hope this helps.
> > > > Edit: left is this hand and right the other one.
> > > 
> > > 
> > > You are an absolute chad! Thanks that solved the issue for me as well! I was so confused as to why this was happening. I wonder if it has anything to do with using a tiling window manager as opposed to a DE?
> > 
> > 
> > Is this still happening on 2.0.5? It should've been fixed, i forgot to mention it in the patch notes 😅
> 
> It is still happening to me. Not sure what is causing it though, although I suspect is might be something to do with my window manager.

idk either, we tested it and someone with the same bug last commit fixed it, so weird. For me on Linux there was never an issue, it's also only a problem on Linux dangit

**Comment by 3rgoProxy** [comment]
> > > > > I have an easier workaround, for me the Apply button would highlight but I could not press it nor the Github or Donate button.
> > > > > I could press the button by doing: `Shift + Left Click`
> > > > > That is it, after that the terminal shows the patches and configuration applying. Hope this helps.
> > > > > Edit: left is this hand and right the other one.
> > > > 
> > > > 
> > > > You are an absolute chad! Thanks that solved the issue for me as well! I was so confused as to why this was happening. I wonder if it has anything to do with using a tiling window manager as opposed to a DE?
> > > 
> > > 
> > > Is this still happening on 2.0.5? It should've been fixed, i forgot to mention it in the patch notes 😅
> > 
> > 
> > It is still happening to me. Not sure what is causing it though, although I suspect is might be something to do with my window manager.
> 
> idk either, we tested it and someone with the same bug last commit fixed it, so weird. For me on Linux there was never an issue, it's also only a problem on Linux dangit

I just installed KDE Plasma to see if the problem persisted in a DE. It works for me with no issues on kde plasma, but not when using AwesomeWM. So I guess it must be some kind of issues caused by WM in linux. I also have window swallowing enabled on Awesome so that could also interfere. Either way, no issue when using a DE at least on my end.

**Comment by zenmaster3000** [comment]
So I have good news and bad news.

The good news is that I (kinda) know what is happening now, the bad news is that it can't be fixed.
Now to the details, I'm also using AwesomeWM and the only way to interact with the buttons in the GUI is doing the Shift+Click. There is another program that doesn't play nice with AwesomeWM and that would be [Polybar](https://github.com/polybar/polybar/wiki/Known-Issues#mouse-interactions-not-working-in-awesomewm).

The way some people workaround this problem is to tell Polybar to set the override-redirect property, this will tell AwesomeWM to ignore. You can recreate this getting the window id

**Comment by MaxLastBreath** [comment]
I'll keep the issue open, hopefully it's useful for someone

**Comment by Madiwka4** [comment]
The issue is still happening for me, unfortunately. Shift + Click does not work either and none of the buttons except for the ones without images work at all (no output in the terminal either). I am running Linux and tried both the AppData and the zip file (although I assume they are both AppImage files anyway). 
For context, I am using Arch Linux with GNOME, my Ryujinx is on Flatpak.

**Comment by MaxLastBreath** [comment]
oh. Probably that may be why too, cuz I remember it was fixed, probably warranted to release a new version soon 2.0.6 with a few new tweaks and benchmarks next week.
