### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa0 in position 5223: illegal multibyte sequence

### ISSUE THREAD

**Issue by yiaya001** [MaxLastBreath/TOTK-mods#67]
Got this error in log while press "APPLY":
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa0 in position 5223: illegal multibyte sequence

Seems like a 'utf-8' problem:
like:
change from:

   open(class_file_name, 'name') 

to:

   open(class_file_name, 'name', encoding='utf-8')

**Comment by MaxLastBreath** [comment]
Pretty much the entire patch was done a few days ago, feel free to test the src code and see if it's fixed, I haven't had the time to test it yet so it would be appreciated.

**Comment by fenggehuafashi** [comment]
Tried win11  with Simplified Chinese language，the ‘gbk’ codec problem still exists at version 1.5.5 . However, I can setup the windows system setting——the language when program do not support Unicode.  Change it to English(US) and enable the Beta(UTF-8) system language setting. At last, it worked.

**Comment by fenggehuafashi** [comment]
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/51372084/1f043a5b-4c57-4dd0-b2df-c8b858eedcf3)

**Comment by fenggehuafashi** [comment]
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/51372084/81ba11fd-4cca-4430-8e3d-433eb9f5db80)
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/51372084/3900f988-21c6-44dc-af10-69ea8f12e76a)
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/51372084/77b293b0-a7c5-439a-8b46-420d9beb2aea)

**Comment by MaxLastBreath** [comment]
Yeah I'm aware of the issue and it should be partially fixed now in version 2.0 however due to the shutdown of the Yuzu emulator version 2 has been delayed.

Also #71

**Comment by 1tsAll1nTheCard** [comment]
> rtially fixed now in version 2.0 how

6
