### ISSUE TITLE
Couldn't find Yuzu Running

### ISSUE THREAD

**Issue by VanitasFR** [MaxLastBreath/TOTK-mods#68]
Hello, i use EA yuzu and when i use TOTK Optimiser to launch the game with applied mods in the console it says couldn't find if yuzu is running, i don't know if this is normal behaviour
[logger.txt](https://github.com/MaxLastBreath/TOTK-mods/files/14001326/logger.txt)

**Comment by MaxLastBreath** [comment]
Normal behavior, the check only confirms if yuzu is running so that the user can close it
