### ISSUE TITLE
steamdeck appimage logger error

### ISSUE THREAD

**Issue by ChillHaw** [MaxLastBreath/TOTK-mods#70]
thanks for your hard work!

1.5.5 won't start on my deck. when I click the appimage, it creates two files and a folder then nothing happens. in the logger it said that GPU was not detected and something wrong as follow:

TIME: 17:10:48,486 - LOGGER - ERROR: Error occurred while fetching or parsing Description.json: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /MaxLastBreath/TOTK-mods/main/scripts/settings/Description.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f801077ca90>: Failed to establish a new connection: [Errno 111] 拒绝连接')

**Comment by MaxLastBreath** [comment]
This error is from opening the appimage too many times, should go away 1 hour approximately after the error, this can happen from too many installations :D
