### ISSUE TITLE
Apply Button doesn't work (DECODE ERROR) (SOLUTION)

### ISSUE THREAD

**Issue by rarikuma** [MaxLastBreath/TOTK-mods#71]
When I press the APPLY button, no mod file is generated and nothing happens.
The version of TOTK Optimizer is 1.5.5.
Terminal displays the following error message.

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "form.py", line 351, in <lambda>
  File "form.py", line 1032, in submit
  File "configparser.py", line 713, in read
  File "configparser.py", line 1036, in _read
UnicodeDecodeError: 'cp932' codec can't decode byte 0x97 in position 3311: illegal multibyte sequence
![Game Bar Captures 2024_01_25 20_22_21](https://github.com/MaxLastBreath/TOTK-mods/assets/135856005/22ac7891-a6a4-4756-9a80-c48d9ca33c52)

**Comment by MaxLastBreath** [comment]
Please use this, ive been trying to fix these errors for a while, its from windows without native utf-8 encoding.
The link below has a fix that fixes my application and every other application with utf-8 dependencies.
https://exploratory.io/note/exploratory/Enabling-UTF-8-on-Windows-hYc3yWL0

**Comment by rarikuma** [comment]
Thanks for the reply.
I have enabled "Beta: Use Unicode UTF-8 for worldwide language support" in the Windows settings and now TOTK Optimizer is able to generate mod files.

**Comment by MaxLastBreath** [comment]
Im glad its all working now, gonna keep this incase others needs a solution as well :)

**Comment by rarikuma** [comment]
However, I have heard of cases where enabling this setting on Windows causes problems with other applications.
As a temporary solution, I enable the "Beta: Use Unicode UTF-8 for worldwide language support" setting only when using TOTK Optimizer to generate mod files,
It would be most desirable if the TOTK Optimizer could fix the problem so that this setting is not needed, and I hope it will happen.
