### ISSUE TITLE
qt-config.json missing

### ISSUE THREAD

**Issue by LunarRuby** [MaxLastBreath/TOTK-mods#72]
Whenever I am trying install the mods, it says that I am missing this file in my directory, and I can confirm that is in fact not there, but for some reason when it tells me to look for totk in my yuzu install, it's there! It's just acting like it's not installed for some reason. Any fix or workaround?

**Comment by MaxLastBreath** [comment]
Hello, are you using a user folder in yuzu? If so, click browse yuzu.exe and select yuzu.exe :). If you are not, just run yuzu once and open TOTK Once and the issue should go away on its own. (For Windows)
