### ISSUE TITLE
Audio is silent when FPS limit is removed on title screen in Yuzu

### ISSUE THREAD

**Issue by rarikuma** [MaxLastBreath/TOTK-mods#73]
I was using a mod file generated by TOTK Optimizer on Yuzu, I encountered a bug where the audio becomes silent when the FPS limit is removed in Yuzu.
As far as I have tested, this problem occurs when the FPS limit is removed at the title screen, and does not seem to occur when the FPS limit is removed after loading the save data.
I recall that this problem also occurred in older versions of ChucksFeedAndSeed's DynamicFPS, but it stopped occurring after an update at some point.
I assume that some fix made by MaxLastBreath has made this problem recur.

**Comment by MaxLastBreath** [comment]
It shouldn't matter at all, the next release will just let you uncap fps natively in the game itself, without relying on yuzu buggy speed uncap
