### ISSUE TITLE
Would like to be able to disable FreeCam om/off assignments on controllers

### ISSUE THREAD

**Issue by rarikuma** [MaxLastBreath/TOTK-mods#75]
The Freecam on/off toggle is assigned to ZL + D-Pad Down on the controller, but would like an update that would allow this to be disabled. This assignment is due to the risk of malfunction.

**Comment by MaxLastBreath** [comment]
It's already been addressed in the upcoming update.

**Comment by rarikuma** [comment]
I see.
Looking forward to the update.

**Comment by rarikuma** [comment]
One more personal opinion.
Down is assigned to the Ctrl key on the keyboard in FreeCam, but I felt that another key would be better.
This is because there are a number of standard yuzu Hotkeys settings that use the Ctrl key, and they are duplicated.
It would be best if all FreeCam key assignments could be determined by the user in an ini file.

**Comment by MaxLastBreath** [comment]
> One more personal opinion. Down is assigned to the Ctrl key on the keyboard in FreeCam, but I felt that another key would be better. This is because there are a number of standard yuzu Hotkeys settings that use the Ctrl key, and they are duplicated. It would be best if all FreeCam key assignments could be determined by the user in an ini file.

it's not something easy to program would take a lot of time and time isn't something i have currently, unfortunately
