### ISSUE TITLE
Ryujinx configuration reset after using the tool.

### ISSUE THREAD

**Issue by LaykaKiro** [MaxLastBreath/TOTK-mods#76]
As it says on the box, did some stuff to configure it, applied the things, then needed to remake my config...

**Comment by MaxLastBreath** [comment]
will be fixed on v 2.0 (soon)

**Comment by LaykaKiro** [comment]
Ah, I see. I'll avoid the mod until then. Thanks for the info!

**Comment by MaxLastBreath** [comment]
No worries, shouldn't take more than a week, I've been working on the ultracam 2.0 full time for the past 3 months
