### ISSUE TITLE
30 FPS limit not working

### ISSUE THREAD

**Issue by zephyan1** [MaxLastBreath/TOTK-mods#78]
It previously worked just fine, but one day I decided to launch the game and it began running at 60 FPS (which isn't stable on my system, hence why I limit it at 30) but no matter what I've tried: Reinstalling yuzu, deleting the mods and reapplying them over and over and over, the game still refuses to cap itself at 30 FPS for some reason.

**Comment by MaxLastBreath** [comment]
The current yuzu version seems to have bugged fps mods, from what i was told in discord
