### ISSUE TITLE
After clicking Apply button, got an Error "FAILED TO CREATE SETTINGS FILE: binary mode doesn't take an encoding argument" in CMD window

### ISSUE THREAD

**Issue by EzioAuditore2020** [MaxLastBreath/TOTK-mods#80]
After clicking Apply button, got an Error "FAILED TO CREATE SETTINGS FILE: binary mode doesn't take an encoding argument" in CMD window. 

Then I checked Yuzu settings, there is no settings applied at all in Systems and Graphics Tabs, all settings are default.

See attached screenshot:
![TOTK Optimizer error 01](https://github.com/MaxLastBreath/TOTK-mods/assets/60751422/ca6fac8f-9aff-439f-9bbe-d94107c00b90)

Is this error something I need to worry about? how to fix it?

**Comment by Uranite** [comment]
Already fixed in https://github.com/MaxLastBreath/TOTK-mods/commit/2e5a61452c5d1a3a42a0c6cf41324598b77651c6
download the build here https://github.com/MaxLastBreath/TOTK-mods/actions/runs/7596722307
