### ISSUE TITLE
21:9 ratio doesn't work perfectly, there are small black bars on 2 sides

### ISSUE THREAD

**Issue by EzioAuditore2020** [MaxLastBreath/TOTK-mods#81]
21:9 ratio doesn't work perfectly, there are small black bars on 2 sides, any idea how to fix it?

![TOTK Optimizer 21-9 not working](https://github.com/MaxLastBreath/TOTK-mods/assets/60751422/092d93bd-fd2d-48f2-8496-04294d65b518)

**Comment by MaxLastBreath** [comment]
Use stretch to window in the emulator
