### ISSUE TITLE
Game freeze on initial loading

### ISSUE THREAD

**Issue by bennydiamond** [MaxLastBreath/TOTK-mods#82]
Using TOTK optimizer 1.5.5

NSP + update 1.2.1

Yuzu EA 4176

Optimizer Preset: High
Yuzu settings: AMD
No other custom changes

System:
CPU 5800X3D
GPU 6900XT
32GB DDR4 3200
Running off SSD

I'm trying to load my save file and on initial loading, the game freeze on loading screen.
The UI elements that usually are loaded second stage on the loading screen (hearts, stamina, rupees, etc.) never appear.
I tried leaving it on the loading screen 10 minutes.
Deleted shaders.
![image](https://github.com/MaxLastBreath/TOTK-mods/assets/6563977/e4b64df5-98df-46d4-ad7c-9bd437be90f1)

Changing "Upscaling Version" from UltraCam to DFPS Legacy does NOT exhibit issues.
Loading game without mods does NOT exhibit issues.

**Comment by MaxLastBreath** [comment]
are you using 1.00 or dfps 1.5.5? use Ultracam

**Comment by bennydiamond** [comment]
Reverted to title update 1.2.0 on TotK and it's all good now.
