### ISSUE TITLE
Yuzu settings not being set right

### ISSUE THREAD

**Issue by nav1206** [MaxLastBreath/TOTK-mods#83]
Hey so when I setup totk optimiser 1080p preset then I go to Yuzu, when I right click on totk and check the graphic settings, every setting other than one is enabled, when clearly there is an optimal setup (as outlined by your original reddit post), is there anything I might be doing wrong, as the optimiser should auto fill totk settings on yuzu, right?

**Comment by Uranite** [comment]
Already fixed in https://github.com/MaxLastBreath/TOTK-mods/commit/2e5a61452c5d1a3a42a0c6cf41324598b77651c6
download the build here https://github.com/MaxLastBreath/TOTK-mods/actions/runs/7596722307
