### ISSUE TITLE
Confused on how mods are applied on Steam Deck

### ISSUE THREAD

**Issue by outofether** [MaxLastBreath/TOTK-mods#85]
I am trying to use your tool on Steam Deck, but not having much luck.  I am using the latest Yuzu EA build, not installed thru emudeck (not sure if that's relevant).  When launching your tool, I notice I am missing the launch button, even when I point it to my nsp game file thru settings.  When I hit apply, it downloads the Steam Deck preset mods, but when I look in the Yuzu mod directory there is nothing there.  I also noticed that the Yuzu qt-config.ini file has been edited, and I see the mods listed under disabledaddons.

**Comment by MaxLastBreath** [comment]
Are no mods present in the yuzu properties?

**Comment by MaxLastBreath** [comment]
The launch button was never intended to be in the linux version, that's why it's missing atm.

**Comment by outofether** [comment]
I had previously installed mods manually by copying them to the yuzu mod directory, but I deleted them a while ago.  I did this thru the context menu available when you right click on the game in Yuzu.  The mod directory is empty, and when I look at the game properties, where mods would normally be listed to enable/disable, the only thing there is my installed 1.1.0 update.

**Comment by MaxLastBreath** [comment]
try 2.0 please :)

**Comment by outofether** [comment]
I will when I get home today and post my results. Thanks for responding so fast! You’re awesome!

**Comment by DavidSok8** [comment]
Did you get it to work? I’m facing the same issue. There are no mods in the main totk mod folder.

**Comment by outofether** [comment]
So, unfortunately, it looks like the issue persists.  It download and applies the mods, however, in Yuzu there are no mods visible in the mod directory.

**Comment by DavidSok8** [comment]
I’m suspecting it’s downloading the mods to another directory. I’m just not certain how we can redirect it back to the Yuzu EA.

**Comment by MaxLastBreath** [comment]
You can also just use the extract option and copy paste the mods over to the mod folder now with 2.0.3

**Comment by outofether** [comment]
> You can also just use the extract option and copy paste the mods over to the mod folder now with 2.0.3

Will try this tonight. 

As DavidSok8 pointed out, I too think it may be saving the mods to a different directory. Is there a config file for the tool that we can look at to verify paths?

**Comment by MaxLastBreath** [comment]
atm you can use the extract option to manually apply stuff if things arent working correctly, it will create the mods in the same directory as the optimizer. I think this was the best solution.
