### ISSUE TITLE
Crash on real hardware on game start if no save present

### ISSUE THREAD

**Issue by aaronson2012** [MaxLastBreath/TOTK-mods#89]
If you are running on real hardware (I have Mariko, no sure if this applies to Ersita) the game crashes if loading without a save present. The crash occurs just after the footstep sounds when and the loading icon appears. If a save is present it works fine. Even when starting a new game.

**Comment by MaxLastBreath** [comment]
oh dang, it crashes in the beginning cutscene? Definitely an issue, I would have to take a look at eventually dangit.
