### ISSUE TITLE
Resolution and FPS issue

### ISSUE THREAD

**Issue by AdnanSoftic** [MaxLastBreath/TOTK-mods#9]
Hi,

Followed you guide on Reddit and downloaded optimizer but I am having issues with resolution and FPS.
Running latest EA 3834 from pineapple. CPU: 5959x GPU: 4080.

I open the optimizer, select options I want like below. However when run the game resolution is low, I believe 720 or 1080p and FPS is limited to 30.
At first I though mods are not working but after testing PS4 layout and First Person mode realized that is not the case.

Is there some additional manual configuration required for the emu or could it be that optimizer is not working with this version of emu?

**Comment by AdnanSoftic** [comment]
UPDATE: Works fine with 1.2, I was running 1.2.1

**Comment by MaxLastBreath** [comment]
Hey, thank you for reporting this, does version 1.2.2 work fine as well for you?

**Comment by AdnanSoftic** [comment]
Unfortunately I did not try it with 1.2.2. When I do I will let you know.
