### ISSUE TITLE
Horrible Performance and Game Crash

### ISSUE THREAD

**Issue by JEmlay** [MaxLastBreath/TOTK-mods#90]
AMD 3970X
RTX 4090
Ryujinx v1.1.1221

With no mods I get a flat 30fps.

With this mod as soon I step out of the 3rd shrine I get 3fps for about 20 seconds then the game crashes.

Are there logs anywhere I can post?

EDIT:
V1.5.5 works fine and I get about 45-50 fps inside, 35fps outside.

EDIT2:
Works fine with Yuzu (latest build).  Getting 60 inside, around 42 outside.  Although the first time I loaded it Link was missing.  I could see only his shadow.  Quit and reloaded then he came back.

**Comment by MaxLastBreath** [comment]
on ryujinx: You cant use anything over the high balanced preset, even the high preset causes issues. This has been mentioned in both the discord and the release notes cheers.

**Comment by JEmlay** [comment]
I'm not using anything higher than that.  So that's not the problem.

**Comment by MaxLastBreath** [comment]
> I'm not using anything higher than that. So that's not the problem.

u can try running the 1080p preset and see if performance is the same or better, ryujinx has issues with the high resolution, since the resolution is coming from the game itself, it isnt externally upscaled.

**Comment by JEmlay** [comment]
1080p without the mod is locked at 30.  1080p should be unhinged on my machine but with the mod I'm in the 20's.  I saw a dip to 13 a couple times.

Now that everyone has the best version of Yuzu I'm just going to use that moving forward for TotK.  But for the sake of whatever this issue is I'll test it with you if you want.

**Comment by MaxLastBreath** [comment]
The new Ryujinx patch from yesterday should have fixed those issues by increasing the game's texture cache. I've personally tested it and experienced much better performance on my end.

**Comment by JEmlay** [comment]
Much better!  Thanks for the update, appreciate it!

**Comment by MaxLastBreath** [comment]
<3
