### ISSUE TITLE
Could you share how to install this and use it on Steam Deck with Yuzu?

### ISSUE THREAD

**Issue by L0WR1D3Rz** [MaxLastBreath/TOTK-mods#92]
As title says. Can't figure out how to run this on my steam deck. Any help is appreciated.

**Comment by MaxLastBreath** [comment]
the steamdeck paths are probably bugged atm, it should be easy regardless just do the steamdeck preset and press -> extract button, copy paste the !!!TOTKOptimizer folder into mods folder of emu, which you can find by right clicking and browse mods.

**Comment by L0WR1D3Rz** [comment]
Thanks I'll try. In terms of expected performance what do you think? Is it
30 with drops still?

Angelo Karaiannis
Mob: +41 79 278 00 25
email: ***@***.***

**Comment by MaxLastBreath** [comment]
should be locked 30 on yuzu and 20fps on ryujinx
