### ISSUE TITLE
A File gets detected by Bitdefender Antivirus

### ISSUE THREAD

**Issue by Kudd1** [MaxLastBreath/TOTK-mods#94]
C:\Users\mekon\Downloads\dd6a2dde-2167-4701-a6ad-9ad70462024c.tmp is infected with Gen:Variant.Mikey.164245.

Its probably a false positive right?

**Comment by MaxLastBreath** [comment]
yeah it has like 6-7k downloads atm, you can just ask in bitdefender's forums for an engineer to inspect and allow it through if you can. It's pretty common with python exes unfortunately. Auto flagged the compiler.
