### ISSUE TITLE
Mod causes the camera to be very zoomed in when starting a new game with no previous save file.

### ISSUE THREAD

**Issue by BParks21** [MaxLastBreath/TOTK-mods#98]
Remove your save file from the save directory and start a new game with the mod. Camera is zoomed in behind link and in the opening cutscenes. The camera isn't fixed until loading a save file. Let the game autosave and then close the emulator and load the file. It's fixed. Tested with 1.2.1 ToTK and default mod settings, Except res. Res is set to 4K. Tested with Yuzu/Suyu. It's as if it's starting a new game with a field of view of 20 instead of the selected and set 50 in the mod settings.

**Comment by MaxLastBreath** [comment]
Please reapply the mods, this was just fixed a few hours ago :)

**Comment by MaxLastBreath** [comment]
Oh and if it still happens after the fixed version is applied just reply here and I'll take a look again tomorrow

**Comment by BParks21** [comment]
Seems fixed thanks!

**Comment by MaxLastBreath** [comment]
No worries! Didn't know this was an issue until like today, would've fixed it sooner haha.

**Comment by BParks21** [comment]
> No worries! Didn't know this was an issue until like today, would've fixed it sooner haha.

Ok so sorry to keep bugging but there seems to be a similar issue with the fps when starting a new game. If I have the mod set to ingame 30 and menu 60 the menu will not enter 60 mode until I load a save file.

**Comment by MaxLastBreath** [comment]
> > No worries! Didn't know this was an issue until like today, would've fixed it sooner haha.
> 
> Ok so sorry to keep bugging but there seems to be a similar issue with the fps when starting a new game. If I have the mod set to ingame 30 and menu 60 the menu will not enter 60 mode until I load a save file.

There's seems to be all kind of jank going on with the tutorial area ... Wonder what's causing it, will investigate

**Comment by BParks21** [comment]
Ok thanks

**Comment by MaxLastBreath** [comment]
> Is the FPS bug in the tutorial now fixed?

Yup

**Comment by BParks21** [comment]
> > Is the FPS bug in the tutorial now fixed?
> 
> Yup

Doesn't appear to be. I recreated the mod with 2.0.4. I have the in game set to 30fps and menus set to 60. As soon as I start a new game and skip the scene with Link and Zelda walking down the stairway and open the start menu it does not jump to 60fps. If I load up a save file and then open the start menu it works. So it is still not functioning correctly in the tutorial section without a save existing in the first place.

**Comment by MaxLastBreath** [comment]
> > > Is the FPS bug in the tutorial now fixed?
> > 
> > 
> > Yup
> 
> Doesn't appear to be. I recreated the mod with 2.0.4. I have the in game set to 30fps and menus set to 60. As soon as I start a new game and skip the scene with Link and Zelda walking down the stairway and open the start menu it does not jump to 60fps. If I load up a save file and then open the start menu it works. So it is still not functioning correctly in the tutorial section without a save existing in the first place. This is with Yuzu.

Oh i gotcha, gonna fix it soon!

**Comment by BParks21** [comment]
Thank you my guy!
