### ISSUE TITLE
Crashes on startup on windows 11

### ISSUE THREAD

**Issue by LMBEN1** [MaxLastBreath/TOTK-mods#99]
Hello, 
The application crashes on startup, on Windows 11, seems like there is a path issue : 

OSError: [Errno 22] Invalid argument: '"C:\\Users\\B&M\\AppData\\Roaming\\yuzu\\sdmc"\\TOTKBenchmark.txt'

log :

Attempting to start Application.
__SystemINFO__
System: Windows
GPU: NVIDIA GeForce RTX 4070 Ti
RAM: 32 GB 3600 MHz and used 28.8%
CPU: Intel(R) Core(TM) i5-14600K

Succesfully loaded api.json.
Found Legacy Emu folder at: C:\Users\B&M\AppData\Roaming\yuzu
Detected a Windows based SYSTEM!
a qt-config.ini file found!
V Camera Sensitivity - 1.0
H Camera Sensitivity - 1.0
Time Speed - 1.0
RSDB Heap size - 1.0
Textures Heap size - 1.0
main
Traceback (most recent call last):
  File "run.py", line 17, in <module>
  File "form.py", line 70, in __init__
  File "form.py", line 711, in load_canvas
  File "modules\benchmarks.py", line 32, in load_benchmark
OSError: [Errno 22] Invalid argument: '"C:\\Users\\B&M\\AppData\\Roaming\\yuzu\\sdmc"\\TOTKBenchmark.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 34, in <module>
TypeError: can only concatenate str (not "OSError") to str
[12328] Failed to execute script 'run' due to unhandled exception!
PS C:\Users\B&M\Desktop\jeux\Yuzu\TOTK mods>

Thank you !

**Comment by MaxLastBreath** [comment]
oh i see that's a yuzu issue, for some reason it saved your path with "" strings

**Comment by MaxLastBreath** [comment]
Should be able to fix it tho

**Comment by LMBEN1** [comment]
:-)

**Comment by LMBEN1** [comment]
I confirm : 2.5.5 solved the issue, many thanks !

**Comment by MaxLastBreath** [comment]
> I confirm : 2.5.5 solved the issue, many thanks !

<333
